### ISSUE TITLE
Error in HotModuleReplacementPlugin after upgrading from 2 to 3.

### ISSUE THREAD

**Issue by wildeyes** [webpack/webpack#5474]
** What is the current behavior?**
    Upgrading from webpack 2 to 3, running`webpack` in the commandline, gives me an error in HotModuleReplacementPlugin.Removing the plugin makes webpack pass.

```
C:\Users\Documents\project\node_modules\webpack\lib\HotModuleReplacementPlugin.js:59
                                        records.chunkModuleIds[chunk.id] = chunk.mapModules(m => m.id);
                                                                                 ^

TypeError: chunk.mapModules is not a function
    at chunks.forEach.chunk (C:\Users\Documents\project
    at Array.forEach (native)
    at Compilation.<anonymous> (C:\Users\Documents\project
    at Compilation.applyPlugins2 (C:\Users\Documents\project\node_modules\tapable\lib\Tapable.js:82:14)
    at sealPart2 (C:\Users\Documents\projectn.js:629:10)
    at Compilation.applyPluginsAsyncSeries (C:\Users\Documents\project
    at Compilation.seal (C:\Users\Documents\projectn.js:579:8)
    at C:\Users\Documents\projects:493:16
    at C:\Users\Documents\project\node_modules\tapable\lib\Tapable.js:225:11
    at _addModuleChain (C:\Users\Documents\projectn.js:481:11)
    at processModuleDependencies.err (C:\Users\Documents\projectn.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[nodemon] app crashed - waiting for file changes before starting...
```
      ** What is the expected behavior?**
        I expected a smooth upgrade :)

webpack v3.5.2
node v7.4.0

**Comment by UchihaVeha** [comment]
After update webpack from 3.4.1 to 3.5.2, HMR doesn't work. In console:
`
[WDS] App updated. Recompiling...
[WDS] App hot update...
`
When i downgrade to 3.4.1, all work fine

**Comment by daraclare** [comment]
Hi, I think this is related, so hope it's okay to add on here. I'm getting an error using the HotModuleReplacementPlugin with Webpack 3.5.2  
`Failed to load resource: the server responded with a status of 404 (Not Found) :3000/__webpack_hmr `
This goes away if I remove the plugin. 
Downgrading to webpack 2 did not help unfortunately, any idea why this could be?

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by UchihaVeha** [comment]
destroy node_modules and npm install - solved my problem with HMR, webpack 3.5.3

**Comment by rabingaire** [comment]
I am also facing the same error.

**Comment by serjp** [comment]
Same error too.

**Comment by brianespinosa** [comment]
I was experiencing this same issue. I can confirm that running `rm -r node_modules` then running `yarn install` or `npm install` afterwards fixed the issue. Thanks for the suggestion @UchihaVeha

**Comment by rodoabad** [comment]
Re-installing does not seem to solve this issue.

**Comment by rodoabad** [comment]
Anyone else still having this issue?

Note: Re-installing DOES NOT solve the current issue.

**Comment by TurboTim** [comment]
Yep I am getting the same error, yarn rm/install not working

**Comment by shelbyspeegle** [comment]
@rodoabad @TurboTim i had this issue too. turns out i needed to remove a globally installed version of `webpack`. hope this helps!

`yarn global remove webpack`
or maybe
`npm remove -g webpack`

**Comment by evilebottnawi** [comment]
This problem happens when you have old version webpack.
Solution:
1. Remove webpack global `npm remove -g webpack`.
2. Clean npm cache `npm cache clear --force`.
3. Install `webpack`  and deps again.
