### ISSUE TITLE
[bug] v1.13.0: Cannot find module 'enhanced-resolve'

### ISSUE THREAD

**Issue by jadbox** [webpack/webpack#2344]
After I updated to 1.13.0, I get the error:
```
Error: Cannot find module 'enhanced-resolve'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/jdunlap/github/vidroll/reportal/node_modules/webpack/bin/convert-argv.js:4:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)```

**Comment by jadbox** [comment]
Although this error goes away in v1.12.15.

**Comment by sokra** [comment]
It's in the dependencies of the package.json... https://github.com/webpack/webpack/blob/webpack-1/package.json#L9

Propably a npm issue... Try reinstalling

**Comment by frankfullstack** [comment]
Reproduce this error with the following dependency:

    "webpack": "^1.13.3"

This is my `package.json` file:

```
{
  "name": "webpack-typescript",
  "version": "0.0.1",
  "description": "",
  "main": "server.js",
  "scripts": {
    "build": "webpack"
  },
  "keywords": [],
  "author": "frankfullstack <frankfullstack@gmail.com>",
  "license": "ISC",
  "devDependencies": {
    "@types/express": "^4.0.34",
    "awesome-typescript-loader": "^3.0.0-beta.3",
    "typescript": "^2.0.10",
    "webpack": "^1.13.3"
  },
  "dependencies": {
    "body-parser": "^1.15.2",
    "cookie-parser": "^1.4.3",
    "cors": "^2.8.1",
    "dotenv": "^2.0.0",
    "express": "^4.14.0"
  }
}
```

My `tsconfig.json` file is the following:

```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "noImplicitAny": false,
        "sourceMap": false
    },
    "exclude": [
        "node_modules"
    ]
}
```

The `webpack.config.js` file is:

```
module.exports = {
    entry: './main.ts',
    output: {
        filename: './bundle.js'
    },
    resolve: {
        extensions: ['', 'ts']
    },
    module: {
        loaders: [
            { test: /.ts$/, loader: 'awesome-typescript-loader' }
        ]
    }
};
```

When I run the `npm run build` script I get the next CLI result:

```
$ npm run build

> webpack-typescript@0.0.1 build C:\Users\frankfullstack\Code\webpack-typescript
> webpack

Hash: e1ae715a9f967276763f
Version: webpack 1.13.3
Time: 134ms
    + 1 hidden modules

ERROR in Cannot find module 'enhanced-resolve/lib/getInnerRequest'
```

Anyone is getting the same error right now?

**Comment by dolanmiu** [comment]
Yes I am having the same issue

**Comment by Heliosophist** [comment]
I was having the same issue with webpack 1.13.3.Installing "enhanced-resolve" with npm fixed the problem.As sokra pointed out, the problem is in webpack's outdated dependency in it's package.json. https://github.com/webpack/webpack/blob/webpack-1/package.json#L9
