### ISSUE TITLE
Hard to debug TypeError: arguments[i].apply is not a function

### ISSUE THREAD

**Issue by BrainCrumbz** [webpack/webpack#2217]
Packages version:
- webpack: 1.12.14
- tapable: 0.1.10

While editing webpack config file we met the following error:

```
<<PROJECT_PATH>>\node_modules\tapable\lib\Tapable.js:164
                arguments[i].apply(this);
                             ^

TypeError: arguments[i].apply is not a function
    at Compiler.apply (<<PROJECT_PATH>>\node_modules\tapable\lib\Tapable.js:164:16)
```

and that seemed a situation similar to issue #697 .

We were able to spot the offending change after some time, but still the message was not at all helpful. In our case, error was due to the following:

``` javascript
config.plugins = [
  // some plugins added here ...
];

// further down

config.plugins.push([
  // another plugin here, but mistakenly added as a whole array
]);
```

The fix was of course to properly add the new plugin as a single item:

``` javascript
config.plugins.push(
  // another plugin here, correctly added as a single item
);
```

Request: try to improve argument checking or anyway improve error messages.

Thanks for your time spent on this great project!

**Comment by resistdesign** [comment]
:+1:

**Comment by theseyi** [comment]
I noticed the exact error as well while attempting to integrate Facebook's Relay with webpack and babel.
The issue in my case was mistakenly adding a reference to the babel-relay-plugin into the plugins array for module loaders in `webpack.config.js` instead of the `.babelrc` file.

**Comment by TheLarkInn** [comment]
I have come across this bug today while trying to creating a custom plugin and importing it for the first time. 

```javascript
plugins: [
    new TypeDocWebpackPlugin(),
    new ForkCheckerPlugin(),
    ...,
    ... 
],
```

Here is the plugin itself. 
```javascript 
function TypeDocWebpackPlugin(pluginOptionsObject) {
}

TypeDocWebpackPlugin.prototype.apply = function(compiler) {
  debugger;

  // Setup callback for accessing a compilation (async)
  compiler.plugin('emit', function(compilation, callback) {

    debugger;

    callback();
  });

}

module.exports = TypeDocWebpackPlugin;
```

**Comment by MoOx** [comment]
Getting this issue (or at least similar message: `arguments[i].apply is not a function`), using nodejs api. webpack() does not throw an error, but instead pass the error (instanceof Error) instead of the "stats" object (where I were trying to call .toJSON() on, so took me a while to find the origin of the issue). This is pretty weird webpack does call instead of throwing, like it usually does (note that I am using webpack 2.1.0-beta.25).

**Comment by p4bloch** [comment]
This also happened in my case with webpack 2.2.0 when returning `[Plugin, Plugin, false, Plugin]` for the plugins list (I am using `flag && new webpack...` for adding plugins conditionally).

Adding `.filter(Boolean)` at the end of the array to send an array like `[Plugin]` effectively solved the issue.

**Comment by SpainTrain** [comment]
@p4bloch *thank you*, this was very difficult to troubleshoot given the opaqueness of the error message

**Comment by luanmuniz** [comment]
I'm having this same problem. Here is a repository with the bug reproducible
https://github.com/luanmuniz/react-bug
