### ISSUE TITLE
[Bug] webpack.IgnorePlugin failing in v2.4.2 but didnt in 2.3.2

### ISSUE THREAD

**Issue by sagiavinash** [webpack/webpack#4721]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
in wepack plugins config i have
`new webpack.IgnorePlugin(/^\.\/locale$/, [/moment$/]),`

when i upgraded to v2.4.1 
```
TypeError: this.contextRegExp.test is not a function
    at IgnorePlugin.checkContext (./node_modules/webpack/lib/IgnorePlugin.js:34:29)
    at IgnorePlugin.checkResult (./node_modules/webpack/lib/IgnorePlugin.js:48:52)
    at IgnorePlugin.checkIgnore (./node_modules/webpack/lib/IgnorePlugin.js:53:11)
    at ContextModuleFactory.applyPluginsAsyncWaterfall (./node_modules/tapable/lib/Tapable.js:208:13)
    at ContextModuleFactory.create (./node_modules/webpack/lib/ContextModuleFactory.js:26:7)
    at iteratorFactory (./node_modules/webpack/lib/Compilation.js:229:12)
    at ./node_modules/webpack/node_modules/async/dist/async.js:3047:16
    at eachOfArrayLike (./node_modules/webpack/node_modules/async/dist/async.js:1039:9)
    at eachOf (./node_modules/webpack/node_modules/async/dist/async.js:1087:5)
    at Object.eachLimit (./node_modules/webpack/node_modules/async/dist/async.js:3109:3)
    at Compilation.addModuleDependencies (./node_modules/webpack/lib/Compilation.js:210:12)
    at Compilation.processModuleDependencies (./node_modules/webpack/lib/Compilation.js:195:8)
    at ./node_modules/webpack/lib/Compilation.js:336:13
    at ./node_modules/webpack/lib/Compilation.js:140:27
    at Array.forEach (native)
    at callback (./node_modules/webpack/lib/Compilation.js:140:13)
    at ./node_modules/webpack/lib/Compilation.js:167:11
    at ./node_modules/webpack/lib/NormalModule.js:300:11
    at ./node_modules/webpack/lib/NormalModule.js:206:11
    at ./node_modules/loader-runner/lib/LoaderRunner.js:370:3
    at iterateNormalLoaders (./node_modules/loader-runner/lib/LoaderRunner.js:211:10)
    at Array.<anonymous> (./node_modules/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (./node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:15)
    at ./node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:69:9
    at ./node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)

```

**If the current behavior is a bug, please provide the steps to reproduce.**
upgrade to webpack 2.4.1 

my production webpack config
https://gist.github.com/sagiavinash/1788b9dbe9d24451167f2b99e3f5c593

**What is the expected behavior?**
Ignore plugin should ignore moment unnecessary locale modules

**If this is a feature request, what is motivation or use case for changing the behavior?**
Its a bug affecting me to upgrade to latest webpack version

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
node - v5.0.0
webpack - 2.4.1

**Comment by martinveith** [comment]
Based on your config you are not providing a RegExp for `contextRegExp`, but an array which contains it. The reason for why this was working with the previous webpack version (v2.3.1) is because it was not using this second argument in the `context-module-factory` step - and so there was no visible error.

This has been fixed a couple of days ago through https://github.com/webpack/webpack/pull/4669, which now correctly takes the second argument `contextRegExp` into account, but can't execute the `test`-fn in your particular case because an array is provided.

So you just have to pass in the RegExp itself and then it should work again!
`new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/)`

**Comment by sagiavinash** [comment]
Thanks @martinveith

**Comment by mistrykaran91** [comment]
I'm having an angular app which is quiet big, so I'm lazily loading chunks and just want to ignore few chunks. So, using IgnorePlugin but unable to match the specific folder/directory. Currently my folder structure is  src/app/modules/platform, so I want to ignore platform folder in ng-build but unable to achieve it. Any help will be appreciated. Thanks in advance.
