### ISSUE TITLE
How to use jquery plugins now?

### ISSUE THREAD

**Issue by hmarcelodn** [webpack/webpack#4783]
Hello,

After migrating from Webpack 1 to 2 my jquery plugins dont work anymore.

I am getting messages like:

**TypeError: $(...).parallax is not a function**

`import 'materialize-css';
export class UserFeatures{
    attached(){
        $('.parallax').parallax();

        $('body').addClass('user-background');      
    }
    detached(){        
        $('body').removeClass('user-background');
    }
}`

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).
