### ISSUE TITLE
Error: "block.getRootBlock is not a function" in webpack 5.60.0

### ISSUE THREAD

**Issue by hmil** [webpack/webpack#14577]
# Bug report

**What is the current behavior?**

Running a build with module federation yields the following error:

```
UnhandledPromiseRejectionWarning: TypeError: block.getRootBlock is not a function
    at getBlockModules (node_modules/webpack/lib/buildChunkGraph.js:219:47)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Unfortunately, my setup is quite "off road". It mixes Angular, and module federation with `@angular-builders/custom-webpack`. So it is difficult for me to provide a minimum repro.

However, I narrowed down the error to version 5.58.0 and above. It works fine with version 5.57.1.

**What is the expected behavior?**

No such error, or a better error message which tells me why `getRootBlock` is not a function.

**Other relevant information:**
webpack version:  5.58.0
Node.js version: 14.17.0
Operating System: mac
Additional tools: module federation, Angular

**Comment by brandones** [comment]
Hi @hmil , can you explain a bit more what you mean by "two different copies of `webpack`"? Where were the two copies located in the directory structure?

I'm having this same problem. And it's occurring in my CI build, which would seem to mean that `npm` is installing things wrong from scratch.

**Comment by hmil** [comment]
One package had declared a dependency on a different version of webpack than the main version declared in my project.

So I ended up with something like:
```
node_modules/webpack
node_modules/foo/node_modules/webpack
```

I may also have had some dependency `yarn link`ed from somewhere else at the time of the issue.

Anyways, make sure there is only one webpack in your node_modules, especially deeper down in the module tree.
