### ISSUE TITLE
Webpack 5.41.0 regression: Systemjs bundle exports are missing

### ISSUE THREAD

**Issue by alk-sdavid** [webpack/webpack#13667]
# Bug report

**What is the current behavior?**

When I bundle a Systemjs module with webpack v5.41.0, exports are missing. For example, if my module exports `someMethod()`, then when I import this System module with Systemjs, the method will be missing:

```js
System.import('my-module').then((myModule) => {
  myModule.someMethod(); // TypeError: myModule.someMethod is not a function
})
```

It seems this issue occurs only when the module have an external dependency.

**If the current behavior is a bug, please provide the steps to reproduce.**

You'll find a repo to reproduce this issue here: https://github.com/alk-sdavid/webpack-systemjs-issue

**What is the expected behavior?**

I guess Systemjs module bundle should work as it was working with v5.40.0, meaning when I import a systemjs module with Systemjs, I should find exported objects in the response.

**Other relevant information:**
webpack version:  5.41.0
Node.js version: 14.17.1
Operating System: MacOS 11.4
Additional tools:
