### ISSUE TITLE
webpack v4.0.0-alpha.1 `-p` and webpack-cli error

### ISSUE THREAD

**Issue by peter-mouland** [webpack/webpack#6162]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
running `webpack --config webpack.config.prod.js -p` throws the error : 

```sh
Error: Cannot find module 'webpack/lib/optimize/UglifyJsPlugin'
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Webpack files: https://gist.github.com/peter-mouland/2a4dc737df271b937281f821cea236f8

run: `webpack --config webpack.config.prod.js -p`

**What is the expected behavior?**
for the files to build.
This worked in ^4.0.0-alpha.0, but only because i was using the in-built cli, not `webpack-cli`

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
```js
    "webpack": "^4.0.0-alpha.1",
    "webpack-cli": "^1.5.3",
```

**Comment by ev1stensberg** [comment]
Hi @peter-mouland , thanks for reporting! Indeed true, this was changed in https://github.com/webpack/webpack/pull/6123 , pushed a fix at https://github.com/webpack/webpack-cli/pull/207/commits/65511f21782f0317fe5c3a5d4b7ea05ce3037e69 ( aka `v2` branch of webpack-cli ), which will be released soon!

**Comment by peter-mouland** [comment]
ah - sorry, i did look for a v2 release and tag, but missed the branch.

for now I can easily remove the `-p` until this is released, so not a problem.

on a related not, should the `-p` option be removed in favour of the `mode: 'production'` or is `-p` still valid in it's own right for webpack v4??

**Comment by ev1stensberg** [comment]
Actually fixed this after you posted an issue, so thank you for reporting the issue! `p` is still valid, and I think `p` is nice, cause it gives you a shortcut on the CLI side, i.e `webpack -p` and you're set

**Comment by sokra** [comment]
`-p` will be the shortcut for `--mode production`
