### ISSUE TITLE
[5.0.0] TypeError: webpack.HashedModuleIdsPlugin is not a constructor

### ISSUE THREAD

**Issue by 2-5** [webpack/webpack#11631]
# Bug report

**What is the current behavior?**
I get this error when building the project after upgrading to 5.0.0:

    [webpack-cli] TypeError: webpack.HashedModuleIdsPlugin is not a constructor

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
const webpack = require('webpack')

// ...

  plugins: [
    // ...

    new webpack.HashedModuleIdsPlugin(), 

    // ...
  ],

// ...
```

**What is the expected behavior?**
At least migration information should be shown on screen or in the docs.

**Other relevant information:**
webpack version: 5.0.0
Node.js version: 14.12.0
Operating System: Windows 10 64 bit
Additional tools: npm

**Comment by blephy** [comment]
I'm getting an other error for me : 

```text
Property 'HashedModuleIdsPlugin' does not exist on type 'typeof import("/Users/blephy/Sites/strict-optimized-react-starter/node_modules/webpack/types.d.ts")'
```

**Comment by jouni-kantola** [comment]
> Update the following options to their new version (if used):
optimization.hashedModuleIds: true ↦ optimization.moduleIds: 'hashed'
https://webpack.js.org/migrate/5/#update-outdated-options

The recommend solution with webpack 5 is using "deterministic", which is the default in production mode.

**Comment by evilebottnawi** [comment]
Answer above, it is breaking change, I think you don’t need this plugin anymore, long term cache is working out of box, anyway if you use this plugin under ids property https://github.com/webpack/webpack/blob/37a676810c70f87bb282103ef3e05e2160040e02/lib/index.js#L290

**Comment by dvopalecky** [comment]
> > Update the following options to their new version (if used):
> > optimization.hashedModuleIds: true ↦ optimization.moduleIds: 'hashed'
> 
> > HashedModulesPlugin ↦ optimization.moduleIds: 'hashed'
> 

If the plugin was called "HashedModuleIdsPlugin", can we make the name consistent in the migration guide https://webpack.js.org/migrate/5/#update-outdated-options which currently states "HashedModulesPlugin". Thanks

**Comment by chenxsan** [comment]
@dvopalecky I've filed a pull request to fix it.
