### ISSUE TITLE
"Uncaught ReferenceError exports is not defined" since 2.2.0-rc.5

### ISSUE THREAD

**Issue by dodekeract** [webpack/webpack#3974]
Bug

Bundle is incorrect and crashes with "exports is not defined".

Unfortunately I can't share steps to reproduce, as the codebase is closed source. However, it definitely worked with 2.2.0-rc.4, so it must be a recent change.

Bundle should be correct and not crash.

**Webpack**: `2.2.0-rc.5`

**Comment by TheLarkInn** [comment]
There is a patch to fix this issue (earlier identified [here](https://github.com/webpack/webpack/issues/3917#issuecomment-272713444)). 

If you'd like to verify as other folks have (PR is still pending review from another maintainer), you can yarn install webpack against that commit referenced in the aforementioned issue. Otherwise, you can keep a lookout for new RC being published.

**Comment by dodekeract** [comment]
@TheLarkInn I'm sure it's the same issue, closing for now, thanks. Just wanted to make sure we're not running into something exotic.

**Comment by TheLarkInn** [comment]
No problem at all. Infact I'll leave open so others can mention here.

**Comment by TheLarkInn** [comment]
Tying to https://github.com/webpack/webpack/pull/3971

**Comment by sokra** [comment]
fixed in https://github.com/webpack/webpack/releases/tag/v2.2.0-rc.6

**Comment by indeyets** [comment]
I still get this with `2.2.0` (no `-rc` suffixes). not sure how to help.

It seems that I get it when I try to import anything from`api/index.js` file, which looks like this:

```
export * from './activities';
export * from './comments';
export * from './common';
export * from './follow';
export * from './lists';
export * from './search';
export * from './session';
export * from './submissions';
export * from './users';
```

**Comment by hellstad** [comment]
@indeyets are you using `babel-loader` with `es2015` preset? I think I was running into the same issue as you. I had to change `"modules": false` to `"modules": "umd"` to get my project working again. I don't think this is right though.

**Comment by indeyets** [comment]
@hellstad I do. Is there separate issue for that?

**Comment by hellstad** [comment]
@indeyets No I don't think there is an issue. I just ran into this problem today. Not 100% the issue is with webpack@2.2.0 as I'm getting the same error after rolling back to 2.2.0-rc3 (which was working for me ~2 weeks ago)

**Comment by stream7** [comment]
Seeing the same issue in `2.2.0`. Works in `2.2.0-rc3`. All other rc versions above that fail.

@hellstad where did you change this `modules` option?

**Comment by hellstad** [comment]
@stream7 babelrc file, it's the options object for the `es2015` preset.

**Comment by albizures** [comment]
Thanks @hellstad!  use `"modules": "umd"` works for me.

**Comment by hellstad** [comment]
For anyone running into this issue, I got my build working with these `babel-loader` options:
```js
const babelLoaderOptions = {
    presets: [
        ['es2015', { loose: true, modules: false }],
        'react'
    ],
    plugins: [
        'transform-class-properties',
        'transform-runtime'
    ]
}
// 'react-hmre' can also be added in dev
```
Also just delete your `.babelrc` file, it was interfering in my build. Configure babel from your webpack config.

You really want `"modules": false` because you don't get tree shaking when you use `"modules": "umd"`

**Comment by ryanwilsonperkin** [comment]
I'm also seeing this issue, with a similar module as @indeyets. I'm on `2.2.1`. If the module just re-exports things I get `Uncaught ReferenceError: exports is not defined` at runtime. 

@hellstad while I'd love to use your recommendation (and get tree-shaking) I can't currently set `modules: false` because there are some circular dependencies in the code that are supported by CommonJS but not by native ES6 modules.

**Comment by arnabrahman** [comment]
Using version 2.2.1 and getting the same problem.

**Comment by mopduan** [comment]
getting the same problem, after upgrade to 2.2.1

**Comment by maniyedidi** [comment]
Using version 2.2.1 and getting the same problem("ReferenceError exports is not defined").

**Comment by arnabrahman** [comment]
Ok the problem was that one of my package file was not es6. I changed it to a es6 format, now it works.

**Comment by MichielLeyman** [comment]
@arnabrahman Could you elaborate on that, please? Stumped on the same issue.

**Comment by arnabrahman** [comment]
i was using [vue-datepicker](https://github.com/hilongjw/vue-datepicker) non es6 version. I replaced it with vue-datepicker es6 version.

**Comment by brotzky** [comment]
For me removing `target: "node"` in my dev webpack config solved the issue.

**Comment by elantion** [comment]
I am facing this same issue. My project use TypeScript 2.3.x, webpack 2.4.1. I change output.libraryTarget to ```umd``` solve my problem. But I don't think this is best practice.

**Comment by elantion** [comment]
I am facing this same issue. My project use TypeScript 2.3.x, webpack 2.4.1. I change output.libraryTarget to ```umd``` solve my problem. But I don't think this is best practice.

**Comment by ndbroadbent** [comment]
I've tried all of the options in this thread, and nothing is working for me. Still getting `ReferenceError: exports is not defined`. 

If I add `import 'babel-polyfill'` to the top of my file, I get this error in the browser:

```
Uncaught TypeError: n(...) is not a function
```

And if I add the `transform-runtime` plugin to my `.babelrc`, I get this crash when I'm compiling:

```
ReferenceError: exports is not defined
```

**Comment by DmytroLapshyn** [comment]
For anyone using TypeScript and babel, if you still face this issue:

**In your tsconfig.json:**
Make sure you have this:
```
    "target": "es2015",
    "module": "es2015",
    "moduleResolution": "node"
```
I have accidentally put `module: "commonjs"` and that was causing this error. 

**In your .babelrc:**
Make sure you have set modules to false and loose to true:
```
"presets": 
[
   [      
      "env",
      {
        "modules": false,
        "loose":  true,
        // ...
```

**Comment by gaearon** [comment]
I can consistently reproduce this in CRA codebase:

```
git clone https://github.com/facebookincubator/create-react-app.git
cd create-react-app
git checkout https://github.com/facebookincubator/create-react-app.git
npm install

npm start
```

Then edit `packages/react-scripts/template/src/App.js` to have an empty block in the `render` method:

<img width="368" alt="screen shot 2017-05-15 at 4 35 15 pm" src="https://cloud.githubusercontent.com/assets/810438/26065651/88de1700-398c-11e7-843a-10bce0827c63.png">

Press save. The browser will reload.

Then edit it to remove the empty block and press save.

You will see the error:

<img width="688" alt="screen shot 2017-05-15 at 4 36 23 pm" src="https://cloud.githubusercontent.com/assets/810438/26065708/a96e1c36-398c-11e7-94ae-c7f1a46d71eb.png">

Unfortunately some internal state appears corrupted because even if I refresh the page, I keep getting the broken bundle. It only gets fixed by a restart of the server.

This is a pretty critical issue for us, as we were planning to cut the release including Webpack 2 this week.

**Comment by gaearon** [comment]
I did some more investigation, and it looked like a caching issue caused by `babel-loader`. I probably had some version of the module cached with CommonJS transform applied, and it was getting embedded into the Webpack 2 bundle (which is incompatible now that I don’t use CommonJS transform).

Deleting `node_modules/.cache` fixed the issue for me. (The path could be different on your system so you can try clearing `/tmp` or temporarily disabling `?cache` option for `babel-loader`.)

**Comment by aparnapatil01** [comment]
gaearon's solution worked for me :+1:

**Comment by MacKentoch** [comment]
Still occurs with webpack 3.

It seems like it depends your babel plugins.

**Comment by decadef20** [comment]
Same in Wepack 3

**Comment by MacKentoch** [comment]
Finally I made it work.
I don't know what was wrong but I reached my personal objectives.
I was working on a starter (or boilerplate, name it as you want) with:
- react
- redux
- react-router 4
- immutable JS
- react hot reload
- webpack 2 (2.6)
- with a server side rendering

[Here is the result](https://github.com/MacKentoch/react-redux-immutable-webpack-ssr-starter)
hope it will help.

**Comment by elyobo** [comment]
Problem also occurs for me, in my case due to importing `joi`; I can't seem to find the right set of rules to transpile it (they don't shipped a transpiled version) but it just works with no problems on `2.2.0-rc.4` (and on none I've tried thereafter) so I've pinned to that version for now.

I have also managed to get it to work with more recent webpack versions by using `joi-browser` (unofficial package) which _is_ already transpiled, so that's probably what I'll end up doing when I get around to upgrading.

**Comment by lukegravitt** [comment]
I got this error when trying to use the CommonChunkPlugin with target: "node" -- apparently that is unsupported - see #1518

**Comment by JMStudiosJoe** [comment]
I am still running into this issue with webpack 3.3.0 
`Uncaught ReferenceError: exports is not defined`
This is a closed source project so can't provide the app code but here is my tsconfig.json and my //webpack.config.js
`
var path = require('path');
var webpack = require('webpack');
const WebpackMd5Hash = require('webpack-md5-hash');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const InlineManifestWebpackPlugin = require('inline-manifest-webpack-plugin');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const ChunkManifestPlugin = require('chunk-manifest-webpack-plugin');

const extractCSS = new ExtractTextPlugin({
    filename: 'distribute-styling.css',
})

module.exports = {
    entry: {
        'vendor': './source/vendor.ts',
        'main': './source/index.ts'
    },
    output: {
        filename: '[name].[chunkhash].js',
        path: path.join(__dirname, '/webpack-build'),
        chunkFilename: '[name].[chunkhash].js'
    },
    plugins: [
        new webpack.optimize.CommonsChunkPlugin({
            name: 'vendor',
            minChunks: Infinity,
        }),
        new WebpackMd5Hash(),
        new InlineManifestWebpackPlugin({
            name: 'webpackManifest'
        }),
        new HtmlWebpackPlugin({
            template: './source/index.html',
        }),
        extractCSS
    ],
    target: 'node',
    devtool: 'source-map',
    resolve: {
        modules: ['source', 'node_modules'],
        extensions: [' ', '.ts', '.d.ts', '.js', '.json', '.scss', '.css']
    },
    module: {
        noParse: [
               /aws-sdk/
        ],
        rules: [
            {
                test: /\.ts/,
                include: [
                    __dirname
                ],
                exclude: [
                    '/react/',
                    '/tests/',
                    '/compiled/'
                ],
                use: [
                    {
                        loader: 'ng-annotate-loader'
                    },
                    {
                        loader: 'babel-loader',
                        options: {
                            presets: ['es2015']
                        }
                    },
                    {
                        loader: 'awesome-typescript-loader'
                    }
                ]
            },
            {
                test: /\.scss$/,
                include: [
                    __dirname
                ],
                exclude: [
                    '/node_modules/',
                    '/source/fonts/'     
                ],
                use: extractCSS.extract({
                    use: ['css-loader', 'sass-loader']
                })
            },
            {
                  test: /\.js$/,
                  include: [
                      '/node_modules/'
                  ],
                  use: 'babel-loader'
            },
            {
                test: /\.json/,
                use: 'json-loader'
            },
            {
                test: /\.(png|jpg|svg)$/,
                use: {
                    loader: 'url-loader'
                }
            },
            {
                test   : /\.(ttf|eot|svg|woff(2)?)(\?[a-z0-9=&.]+)?$/,
                use : 'file-loader'
            }
        ]
    }

}
`

//tsconfig.json
I have changed target and modules to other values es5 es2015 with no success 
`
{
	"compilerOptions": {
		"target": "es2016",
		"modules": "es2016",
		"moduleResolution": "node",
		"sourceMap": true,
		"emitDecoratorMetadata": true,
		"experimentalDecorators": true,
		"lib": [ "es2015", "dom" ],	
		"noImplicitAny": true,
		"allowJs": true,
		"suppressImplicitAnyIndexErrors": true
	},
	"files": [
		"../typings/tsd.d.ts",
		"./source/swagger/backend.d.ts"
	]
}
`
the error is in the compiled main.js 
`
exports.ids = [0];   //ERROR IS HERE EXPORTS IS UNDEFINED 
exports.modules = [
/* 0 */
/***/ (function(module, exports) {

module.exports = require("path");

/***/ }),
/* 1 */
/***/ (function(module, exports) {

module.exports = require("util");

/***/ }),
/* 2 */
/***/ (function(module, exports, __webpack_require__) {

try {
  var util = __webpack_require__(1);
  if (typeof util.inherits !== 'function') throw '';
  module.exports = util.inherits;
} catch (e) {
  module.exports = __webpack_require__(956);
}
`

Thank you in advance for any help

**Comment by lukegravitt** [comment]
@JMStudiosJoe See my comment just above yours. This is the error you get when using CommonsChunkPlugin and targeting node.

**Comment by JMStudiosJoe** [comment]
@lukegravitt thank you for pointing that out is there a solution though or just stop using CommonsChunkPlugin? or target something else?

**Comment by lukegravitt** [comment]
If you are writing a Node server app (or Electron app), the plugin isn't doing much for you as clients shouldn't be downloading/caching the chunks anyway. If you aren't writing a Node app, remove the target (webpack will error if you are using of fs, path or other Node modules though).

**Comment by JMStudiosJoe** [comment]
@lukegravitt yes getting a ton of those errors now since this is a client side app. I have changed the target to web and going to try and get rid of these errors

**Comment by JMStudiosJoe** [comment]
@lukegravitt was able to get passed the exports not defined error by changing `target: 'web'` instead of `target: 'node'` and then using the webpack-node-externals in externals but now dealing with these two errors

<img width="714" alt="screen shot 2017-07-28 at 3 44 16 pm" src="https://user-images.githubusercontent.com/4028643/28738968-c93e5ac2-73ab-11e7-9181-e0246992232e.png">

**Comment by laion220995** [comment]
Hi!
I have same bug

my webpack.base.config:
`const path = require('path')
// const projectRoot = path.resolve(__dirname, '../')
const vueConfig = require('./vue-loader.config')
function resolve(dir) {
  return path.join(__dirname, '..', dir)
}
module.exports = {
  devtool: 'source-map',
  entry: {
    app: './src/client-entry.js',
    vendor: ['vue', 'vue-router', 'vuex', 'vuex-router-sync', 'vue-masked-input', 'vue-google-autocomplete', 'vue-head', 'axios']
  },
  resolve: {
    modules: [path.resolve(__dirname, 'src'), 'node_modules'],
    extensions: ['.js', '.vue'],
    alias: {
      'src': path.resolve(__dirname, '../src'),
      'assets': path.resolve(__dirname, '../src/assets'),
      'components': path.resolve(__dirname, '../src/components'),
      'page': path.resolve(__dirname, '../src/page'),
    }
  },
  output: {
    path: path.resolve(__dirname, '../dist'),
    publicPath: '/dist/',
    filename: 'client-bundle.[chunkhash].js',
    libraryTarget: 'commonjs'
  },
  module: {
    rules: [
      {
        enforce: 'pre',
        test: /\.js$/,
        loader: 'eslint-loader',
        exclude: /node_modules/
      },
      {
        test: /\.css$/,
        use: [
          {loader: "style-loader"},
          {loader: "css-loader"}
        ]
      },
      {
        enforce: 'pre',
        test: /\.vue$/,
        loader: 'eslint-loader',
        exclude: /node_modules/
      },
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: vueConfig
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/,
        options: {
          presets: [
            [
              "es2015",
              { loose: true, modules: false }
            ]
          ],
          plugins: ['transform-class-properties', 'add-module-exports', 'transform-es2015-modules-commonjs', 'transform-runtime']
        }
      },
      {
        test: /\.(png|jpg|gif|svg)$/,
        loader: 'file-loader',
        options: {
          name: '[name].[ext]?[hash]'
        }
      }
    ]
  }
}`

my webpack.client.config: 

`const webpack = require('webpack')
const merge = require('webpack-merge')
const base = require('./webpack.base.config')
const vueConfig = require('./vue-loader.config')
const HTMLPlugin = require('html-webpack-plugin')
const SWPrecachePlugin = require('sw-precache-webpack-plugin')

const config = merge(base, {
  target: 'web',
  resolve: {
    alias: {
      'create-api': './create-api-client.js'
    }
  },
  plugins: [
    // strip dev-only code in Vue source
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'development'),
      'process.env.VUE_ENV': '"client"'
    }),
    // generate output HTML
    new HTMLPlugin({
      template: 'src/index.template.html'
    })
  ]
})

if (process.env.NODE_ENV === 'production') {
  config.plugins.push(
    // minify JS
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false
      }
    }),
    // auto generate service worker
    new SWPrecachePlugin({
      cacheId: 'vue-hn',
      filename: 'service-worker.js',
      dontCacheBustUrlsMatching: /./,
      staticFileGlobsIgnorePatterns: [/index\.html$/, /\.map$/]
    })
  )
}

module.exports = config
`
I rly need help, I fight over the problem for two days already

**Comment by feiyang0117** [comment]
.babelrc ->change false to "commonjs",then i solve it.
{
    "presets": [
        ["env", {
            "modules": "commonjs"
        }],
        "stage-2"
    ],
    "plugins": ["transform-runtime"],
    "comments": false,
    "env": {
        "test": {
            "presets": ["env", "stage-2"],
            "plugins": ["transform-es2015-modules-commonjs", "dynamic-import-node"]
        }
    }
}

**Comment by JaakkoKarhu** [comment]
I am running to the same issue on app built with react-create-app. I modified the presets as @feiyang0117 advices. It removed the error, but the exported objects are not imported, getting undefined back.

**Comment by marlonmarcello** [comment]
I think I have the most simple set up and I'm still getting this error.
`//package.json
"devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-preset-env": "^1.6.1",
    "webpack": "^3.10.0"
  },`
`\\webpack.config.js
module.exports = {
  target: 'web',
  entry: "./src/es6/wtc-swearjar.js",
  output: {
    path: path.resolve(__dirname, "dist"),
    filename: 'bundle.js
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /(node_modules|bower_components)/,
        loader: "babel-loader",
        options: {
          presets: ["env"]
        }
      }
    ]
  }
}`

**Comment by jacklinton** [comment]
A solution for me anyway was change babel-loader config, under plugins, ```['transform-runtime', { "polyfill": false }]```

**Comment by jeron-diovis** [comment]
All the same even with webpack@3. Helps only `plugins: [ ['transform-runtime', { "polyfill": false }] ]` in babel config. 

If polyfill is needed, it's possible to install `babel-polifyll` pkg separately and explicitly import it in app.

**Comment by samgos** [comment]
@jacklinton's solution worked like a charm!

**Comment by Venryx** [comment]
Had the same issue, with Webpack 3.8.1. Fixed using the `polyfill:false` code above.

**Comment by Venryx** [comment]
I got this issue again, and while the `polfill:false` code above did fix it, it caused another issue for me. ("Accessors not supported!" error from babel) I'm not sure why that error wasn't occurring earlier, but I didn't want to dig into all the details to figure it out.

Instead, I just upgraded to Babel 7, and it appears to have solved the issue. Nice and easy fix in my case. :)

**Comment by AnalyzePlatypus** [comment]
I had the same issue in a Vue CLI project. 
What a Heisenbug.

The issue went away when I (in a bout of frustration)  deleted by `.babelrc` and restored `babel.config.json` to the default settings. 
Is anyone else out there as confused about Babel (and Webpack) as I am?

**Comment by jacobbogers** [comment]
any progress on this issue?

**Comment by papiro** [comment]
@AnalyzePlatypus Babel is a mess. I can't wait until we drop support for IE11.
