### ISSUE TITLE
unused default export not marked as unused, so isn't tree-shaken away

### ISSUE THREAD

**Issue by trullock** [webpack/webpack#20537]
### Bug Description

**Summary**

An export is ending up in the initial chunk instead of a dynamically imported chunk, and I don't know why or how to move it.

It is not used in the initial chunk, but isn't marked as so.

**Details**

I'm using vue-loader to import a vue page

vue uses a default export to define the page script
my page also has named exports for other reasons which are out-of-scope here

when I import the named export only into my app, the chunk also ends up with the unused default export, however its not marked as unused, and so it doesn't get removed/tree-shaken

Vue page:

```
<script>
export const opts = {
	route: '/test',
	title: 'I am a test'
}

export default {
	data() { return {
		"I": "Should not be inside the initial bundle"
	} }
}
</script>
<template>
	Testing 123
</template>
```

The chunk for the dynamically imported view page is:

```
"use strict";
(self.webpackChunkwebpack_test = self.webpackChunkwebpack_test || []).push([
  [434],
  {
    262(t, e) {
      e.A = (t, e) => {
        const s = t.__vccOpts || t;
        for (const [t, c] of e) s[t] = c;
        return s;
      };
    },
    434(t, e, s) {
      (s.r(e), s.d(e, { default: () => n, opts: () => c.p }));
      var c = s(121);
      const n = (0, s(262).A)(c.A, [
        [
          "render",
          function (t, e, s, c, n, r) {
            return " Testing 123 ";
          },
        ],
      ]);
    },
  },
]);
```

The default export isn't in there, but I guess thats because its in the initial chunk so thats not the real issue here.

The initial chunk has:

```
...
    n = {
      121(e, t, r) {
        r.d(t, { A: () => n, p: () => o });
        const o = { route: "/test", title: "I am a test" },
          n = {
            data: () => ({ I: "Should not be inside the initial bundle" }),
          };
      },
    },
...
```

which contains the unused default export. Why?

In dev mode:

```
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = ({
  data() {
    return {
      "I": "Should not be inside the initial bundle"
    };
  }
});
```

So it doesn't think its an unused export, why?

### Link to Minimal Reproduction and step to  reproduce

https://github.com/trullock/webpack-mcve

```
> npm i
> webpack
```

### Expected Behavior

unused default export from vue page should be marked as unused, and not included in the initial chunk.
It should be inside the dynamically loaded chunk, as thats where it's used

### Actual Behavior

"unused" default export ends up in initial chunk

### Environment

```shell
System:
    OS: Linux 6.8 Zorin OS 17.3 17.3
    CPU: (32) x64 AMD Ryzen 9 9950X 16-Core Processor
    Memory: 41.08 GB / 60.47 GB
  Binaries:
    Node: 23.6.0 - /home/trullock/.nvm/versions/node/v23.6.0/bin/node
    npm: 11.5.2 - /home/trullock/.nvm/versions/node/v23.6.0/bin/npm
  Packages:
    babel-loader: ^10.0.0 => 10.0.0 
    html-webpack-plugin: ^5.5.0 => 5.6.6 
    vue-loader: ^17.4.2 => 17.4.2 
    webpack: ^5.104.1 => 5.105.2 
    webpack-bundle-analyzer: ^5.1.0 => 5.2.0 
    webpack-cli: ^6.0.1 => 6.0.1 
  Global Packages:
    webpack-cli: 6.0.1
    webpack: 5.103.0
```

### Is this a regression?

None

**Comment by ayaan-mirza7** [comment]
Hi  Can  you assign it to me please! I would be glad to work on it

**Comment by revaarathore11** [comment]
@trullock please assign me I want to work on it!

**Comment by Ritwikcp-ctrl** [comment]
What is this sir, I am unable to understand this , What kind of bug is this ....Where i could see this ? 
Would be great if you make  a bit clear.
Thank You .
Love to solve this.

**Comment by shoryax** [comment]
@trullock, I’ve fixed the issue and it seems to be working fine locally, but when I ran `yarn test` my Mac actually crashed not sure if I messed something up or if there’s anything special I should know about running the full test suite — did i miss a step or is this a known issue?

**Comment by alexander-akait** [comment]
@shoryax I don't know what are you fixed, there are no bugs, only wrong configuration for split chunks

**Comment by trullock** [comment]
> [@shoryax](https://github.com/shoryax) I don't know what are you fixed, there are no bugs, only wrong configuration for split chunks

Theyre bots

**Comment by alexander-akait** [comment]
@trullock Yeah, I will look deeply on your problem soon

**Comment by trullock** [comment]
Thank you, much appreciated.

**Comment by shoryax** [comment]
firstly, @alexander-akait i'm not a bot and thanks for looking at this! I understand you might see this as a configuration issue rather than a bug. Could you point me to what the correct splitChunks configuration would be to achieve the expected behavior? I'd like to understand the intended approach before continuing with the PR.
Just to clarify what I was trying to fix — this is the issue @trullock raised: a Vue SFC has both a named export (opts) and a default export (the component). The app only statically imports the named export, and dynamically imports the full component. The default export ends up in the initial chunk without being marked as unused, so it never gets tree-shaken.
I traced it to getReferencedExports in HarmonyExportImportedSpecifierDependency when vue-loader's intermediary file does export * from "./module" and webpack can't statically determine all exports, it falls into dynamic-reexport mode and returns EXPORTS_OBJECT_REFERENCED, marking everything including default as used. But export * never re-exports default per the ES spec, and mode.ignored already contains "default" — it just wasn't being respected in that code path.
Happy to close the PR if this is intentional behavior or better solved through configuration!

**Comment by alexander-akait** [comment]
@shoryax Was your code generated by AI?

**Comment by shoryax** [comment]
@alexander-akait no, i wrote it. i’ve been looking at this project for a while, so i reviewed other issues and tried to understand the overall idea of what it does. however, i did use ai to get a general overview of this particular chunks thing and what was happening in this particular issue.

**Comment by hai-x** [comment]
It looks like this is the same issue discussed in https://github.com/webpack/webpack/issues/20288, about unused export statement ends up being generated in the initial chunk. For reference, here’s the previous comment: https://github.com/webpack/webpack/issues/20288#issuecomment-3730319094. Does it make sense to you?

If not, let me explain more: 

In your case with `vue-loader`, it splits a `Vue` SFC into two separate modules: one for the `template` and one for the `script`. The SFC module then will re-exports those proxied modules.

As shown in your code, you’re importing the module synchronously on line 1: `import { opts as PageTest } from './test.vue'`. Because this is a static import, `webpack` includes all exports from the `<script>` part of SFC file in the initial chunk, so the unused default export will also be included.

**Comment by trullock** [comment]
Yes this looks the same, thanks for linking.

Is there a solution that doesnt invoke splitting the code into multiple files?

**Comment by neoncube2** [comment]
I've just posted my custom loader: https://github.com/webpack/webpack/issues/20288#issuecomment-3989735220 :)

@shoryax While I can't speak for @alexander-akait, the `webpack` repo has been having issues lately where people keep commenting saying that they would love to work on the issue but they don't understand, they  want to work on the issue but need clarification on what's remaining to be fixed (even though what's remaining is very clear), or that they've fixed the bug (even though there is no bug, and they haven't provided a PR).

Some of these people seem like they're probably real people who are eager to get to work but aren't at the point where they're able to meaningfully contribute, so their comments end up feeling spammy, and others feel like straight up bots. It's a tricky situation, and one that I'm afraid open source is going to suffer from more and more.

The two comments right before your original comment are good examples, but this has been happening to essentially every bug or feature request that's been raised lately.

Anyway, just FYI :)  It's never fun to be called a bot, but unfortunately the repo has been being hit with a lot of bot-like comments lately, so I think we've become a bit jaded XD

**Comment by neoncube2** [comment]
@shoryax  Also, for what it's worth, the effort is appreciated :)

(Anyway, I'll stop clogging up this issue with comments, now XD)

**Comment by Ritwikcp-ctrl** [comment]
@neoncube2 .....Not to worry sir , our contribution will lead to Excellence.
sorry for the comment .

**Comment by shoryax** [comment]
@neoncube2 thanks for the context, that's really helpful! I'll look into #20288 and see if there's a better approach.

**Comment by neoncube2** [comment]
@Ritwikcp-ctrl No worries! :)

I know that getting started on open source stuff can be difficult.

My advice would be:
* Find an easy bug to fix that you don't need to ask questions about.
* After you've fixed the bug, open a PR and ask for it to be reviewed.
* There's usually no need to ask if you can work on a bug. Just work on it, and if you're able to fix it, great, and if not, you can just move on and work on something else.

Wish you well! ^_^

**Comment by neoncube2** [comment]
@shoryax, The conclusion from #20288 was that a fix is probably too esoteric to include in the core webpack code, and that this issue is probably better fixed via a loader. 

If the loader that I ended up writing proves to work well, then I would love for it to eventually be linked to from the webpack documentation, or perhaps if a lot of people end up using it, we can re-evaluate whether including a fix in core makes sense.

**Comment by neoncube2** [comment]
@shoryax By the way, if you're looking around for things to work on, I think there's a lot of (somewhat complicated) things to do in https://github.com/terser/terser, although I'm not sure how much bandwidth that package's maintainer has to review PR's.

**Comment by hai-x** [comment]
I think we can move this issue to the discussion because webpack currently does not plan to implement this `treeshaking` way and it will introduce many extreme bad cases, making the code unstable.

**Comment by trullock** [comment]
I dont really see why this shouldn't be a core feature but I wont argue.
Thanks for everyones input so far

**Comment by hai-x** [comment]
@trullock Sorry, what I mean is that it’s expected that the default export has not been tree-shaken. I’m not saying we will never support it, just that we don’t plan to support it at the moment. It’s a great feature, and it seems that `Turbopack` supports it through module splitting, but I think it would require a significant amount of work to implement.

**Comment by alexander-akait** [comment]
@hai-x Let's open this issue open and mark as a feature

**Comment by BitWiseNotation** [comment]
Hi everyone,

I’ve been reading through the discussion and the related issue (#20288) to better understand the behavior here.

From what I understand, the root cause is that vue-loader generates an intermediary module that uses `export *`, which causes webpack to enter dynamic-reexport mode. In this mode, `getReferencedExports()` conservatively marks the exports object as referenced, so the default export is considered used and cannot be tree-shaken.

Since modifying the core behavior could introduce edge cases, I’m curious whether a loader-based approach that rewrites `export *` into explicit named exports would be a viable solution for this scenario.

I’m currently exploring the module graph logic around `HarmonyExportImportedSpecifierDependency` to understand how webpack determines referenced exports. If there are recommended areas of the codebase to study for this, I’d appreciate any guidance.

Thanks for the detailed explanations so far!

**Comment by trullock** [comment]
@BitWiseNotation thanks for your attention on this. Fixing it would enable me to drasticallly improve the load time of my app

**Comment by neoncube2** [comment]
@BitWiseNotation I think my [webpack-import-splitter-loader](https://github.com/neoncube2/webpack-import-splitter-loader) project should handle this, once some bugs are worked out :)

**Comment by trullock** [comment]
@neoncube2 Have you had a chance to look at my repo which wasn't working? Thanks

**Comment by neoncube2** [comment]
@trullock It looks like @alexander-akait might be working on an experimental flag to enable some behaviour that might help your use case: https://github.com/webpack/webpack/commit/45c7753f7e8d1a5e92bcd984d2c8563f95a56a86

(Thanks, @alexander-akait! I'm very happy to see this possibly working its way into core ^_^)

I've also been slowly improving [webpack-import-splitter-loader](https://github.com/neoncube2/webpack-import-splitter-loader), but it's still a ways from being usable, I'm afraid, especially for your use case with Vue.

**Comment by alexander-akait** [comment]
Yeah, not sure it will be in the next release, but I think we can include it in the next after the next, also you can see the branch, and you can try it, I will add examples later

**Comment by trullock** [comment]
@alexander-akait @neoncube2 great, thanks!

Is this likely to work for my use case right now?

How can I test it?

Thanks

**Comment by neoncube2** [comment]
@alexander-akait Awesome :)

Any chance that you could make a PR for that branch, so that `github-actions` will spit out a pre-built package that I can test? (Like in https://github.com/webpack/webpack/pull/21123#issuecomment-4643565752, for example)

**Comment by neoncube2** [comment]
@alexander-akait Just a reminder about making a (draft?) PR for this, if you have time and it makes sense :)

**Comment by trullock** [comment]
Hi guys, appreciate everyone's a volunteer but is there any movement on this?

This feature could really improve my webapp and users' experience.

LMK if I can help

**Comment by alexander-akait** [comment]
Please try https://github.com/webpack/webpack/pull/21462

**Comment by trullock** [comment]
Oh brilliant, thanks.

Forgive my webpack development inexperience, whats the best way for me to test that? Check out your commit and replace the contents of my node_modules/webpack with it?

Thanks

**Comment by alexander-akait** [comment]
You can use it just from GitHub by providing repo and branch, I will not included this pr in the future minor release, want to tests it more and think, but feel free to provide any feedback

**Comment by trullock** [comment]
Ah ok, thanks.

I've updated my MVCE here https://github.com/trullock/webpack-mcve/tree/webpack but unfortunately it doesn't seem to have changed. The async loaded exports are still in the initial bundle :(

**Comment by neoncube2** [comment]
@alexander-akait I'm excited for https://github.com/webpack/webpack/pull/21462 ! :)

It looks like that PR currently doesn't play well with `HtmlWebPackPlugin`, though, even with `experiments.moduleSplitting` off.

 After compiling, my `index.html` looks like this:

```html
var _ = eval("require")("C:\\xampp\\htdocs\\mylittlewordland-frontend\\src\\.yarn\\cache\\lodash-npm-4.17.21-6382451519-c08619c038.zip\\node_modules\\lodash\\lodash.js");module.exports = function (templateParams) { with(templateParams) {return (function(data) { var __t, __p = '', __j = Array.prototype.join; function print() { __p += __j.call(arguments, '') } __p += '<!doctype html>\r\n<html>\r\n\r\n<head>\r\n<meta charset="utf-8">\r\n<title>My Little Word Land</title>\r\n<base href="/">\r\n<meta name="viewport" content="width=device-width,initial-scale=1">\r\n\r\n<link rel="preconnect" href="https://d1syy4fa7evm13.cloudfront.net">\r\n\r\n	\r\n<style>\r\n		#app {\r\n			display: none;\r\n		}\r\n</style>\r\n\r\n	\r\n

// (etc.)
```

`HtmlWebPackPlugin` config:

```js
new HtmlWebPackPlugin({
	template: './index.html',
	publicPath: FRONTEND_FILES_URL,
	templateParameters: {
		publicPath: FRONTEND_FILES_URL,
		isProduction: isProduction
	},
	inject: false
}),
```

The project compiles fine with webpack 5.108.4

**Comment by neoncube2** [comment]
@alexander-akait Also, if my template `index.html` file contains a `<script>` tag, like so:

```html
<script>
	alert('hello');
</script>
```

I get errors like this when compiling:

```
ERROR in   Error: Child compilation failed:
  Module parse failed: Expecting Unicode escape sequence \uXXXX (1:1)
  You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loader  s
  > \r\n alert(\'hello\');\r\n
  ModuleParseError: Module parse failed: Expecting Unicode escape sequence \uXXXX (1:1)
  You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loader  s
  > \r\n alert(\'hello\');\r\n
      at handleParseError (C:\xampp\htdocs\mylittlewordland-frontend\src\.yarn\__virtual__\webpack-virtual-7913240525\0\cache\webpack-https-5ee891159f-8d88b9bff5.z  ip\node_modules\webpack\lib\NormalModule.js:1593:19)
      at C:\xampp\htdocs\mylittlewordland-frontend\src\.yarn\__virtual__\webpack-virtual-7913240525\0\cache\webpack-https-5ee891159f-8d88b9bff5.zip\node_modules\we  bpack\lib\NormalModule.js:1743:5
      at processResult (C:\xampp\htdocs\mylittlewordland-frontend\src\.yarn\__virtual__\webpack-virtual-7913240525\0\cache\webpack-https-5ee891159f-8d88b9bff5.zip\  node_modules\webpack\lib\NormalModule.js:1292:11)
      at C:\xampp\htdocs\mylittlewordland-frontend\src\.yarn\__virtual__\webpack-virtual-7913240525\0\cache\webpack-https-5ee891159f-8d88b9bff5.zip\node_modules\we  bpack\lib\NormalModule.js:1445:5
      at C:\xampp\htdocs\mylittlewordland-frontend\src\.yarn\__virtual__\webpack-virtual-7913240525\0\cache\webpack-https-5ee891159f-8d88b9bff5.zip\node_modules\we  bpack\lib\loaders\LoaderRunner.js:704:3
      at iterateNormalLoaders (C:\xampp\htdocs\mylittlewordland-frontend\src\.yarn\__virtual__\webpack-virtual-7913240525\0\cache\webpack-https-5ee891159f-8d88b9bf  f5.zip\node_modules\webpack\lib\loaders\LoaderRunner.js:326:9)
      at C:\xampp\htdocs\mylittlewordland-frontend\src\.yarn\__virtual__\webpack-virtual-7913240525\0\cache\webpack-https-5ee891159f-8d88b9bff5.zip\node_modules\we  bpack\lib\loaders\LoaderRunner.js:350:3
      at Object.processResource (C:\xampp\htdocs\mylittlewordland-frontend\src\.yarn\__virtual__\webpack-virtual-7913240525\0\cache\webpack-https-5ee891159f-8d88b9  bff5.zip\node_modules\webpack\lib\NormalModule.js:1395:14)
```

(This is also with `experiments.moduleSplitting` not enabled)

**Comment by alexander-akait** [comment]
Hm, interesting I will take a look, thanks for feedback

**Comment by alexander-akait** [comment]
@neoncube2 looks like it is due our new logic (we support html modules out of box if you don’t have any loader), but looks like you faced with the edge case, maybe you can provide a GitHub repository to see where it happens, thanks

**Comment by trullock** [comment]
I don't fully (or even slightly) understand what I'm doing here, but I think I've tracked my issue down to this:

My two exports are correctly identified as candidates in `ModuleSplittingPlugin.tapParser`, then in `splitModules` `info.namespaceConsumers.length === 1`, so we end up in `facadeSplit`. In there, the call to `analyze(module)` returns a null candidate, so it doesn't get split.

The reason for that is `candidate.referenced` contains `__export__` which I'm gonna guess/reach is because of the webpack module wrapping that happens, so `const __WEBPACK_DEFAULT_EXPORT__ = (__exports__);` or related syntax makes my default export be referenced, even though really it isn't

Does that make sense/am I on the right track? No idea what to do about this as I'm completely out of my depth

**Comment by neoncube2** [comment]
@alexander-akait I've filed a new issue for the error that I encountered: https://github.com/webpack/webpack/issues/21490 :)

**Comment by neoncube2** [comment]
@alexander-akait I tried out https://github.com/webpack/webpack/pull/21462 again, but at least for my project, there seems to be no size difference between `moduleSplitting: true` and `moduleSplitting: false` (the output files are binarily the same).

I'm not sure that I'm setting `moduleSplitting: true` correctly, though. My `webpack.config.js` is like this:

```js
{
	entry: {
		main: './index.jsx',
	},
	mode: 'production',
	module: {
		rules: [
			{
				test: /\.(js|jsx|mjs)$/,
				...
			}
		]
	},
	experiments: {
		moduleSplitting2: true
	},
	...
};
```

**Comment by alexander-akait** [comment]
@neoncube2 sorry for delay, you need more configuration, I will add examples soon so you can try it again, sorry again

**Comment by alexander-akait** [comment]
I want to ship it for the next minor release

**Comment by neoncube2** [comment]
@alexander-akait No problem; I figured it might be a configuration issue :)

**Comment by trullock** [comment]
Is my issue also configuration related?

**Comment by Gambit-Checkmate** [comment]
Hi, I’d like to investigate why an unused default export is not tree-shaken. I can create a minimal fixture that demonstrates the retained export and add a regression test before changing the optimization path. Is this still available for a community PR?

**Comment by trullock** [comment]
Genuinely intrigued as to what the hell is going on in this thread...

**Comment by TanishaJaiswal-web** [comment]
i would like to work on this issue . Feel free to assign it to me!

**Comment by prabhjeet16** [comment]
> Hi Can you assign it to me please! I would be glad to work on it



> What is this sir, I am unable to understand this , What kind of bug is this ....Where i could see this ?
> Would be great if you make a bit clear.
> Thank You .
> Love to solve this.

---------------------------------------------------------------------------------------------------------------------------------------------

This isn't really a traditional bug where the application crashes or behaves incorrectly.

The issue is about bundle optimization. The author noticed that a Vue component's default export is being included in the initial bundle even though it's only needed through a dynamic import later.

In other words, webpack is keeping some code in the main bundle that appears unused during the initial load, which can increase bundle size and affect loading performance.

The interesting part is that webpack maintainers later explained this is currently more of a limitation/feature request around module splitting than a straightforward bug. The challenge is determining whether exports that are only used asynchronously can be safely moved into separate chunks without introducing other edge cases.

If you're trying to understand it locally, the reproduction repository linked by the author is probably the best place to start. Build it, inspect the generated bundles, and compare where the named export and default export end up.

**Comment by BitWiseNotation** [comment]
can you assign me as well on this I would like to work on it.

**Comment by neoncube2** [comment]
@alexander-akait Just a ping about this.

Let me know if you have time to add an example for how to configure this properly, and I'd be happy to test again :)

**Comment by trullock** [comment]
Same, I could really benefit from this, keen to progress it in whatever way I can
