### ISSUE TITLE
dependOn with multiple entry points and dynamic imports broken in 5.19.0

### ISSUE THREAD

**Issue by davidmerrique** [webpack/webpack#12562]
# Bug report

**What is the current behavior?**

Getting errors after updating to 5.19.0

`Uncaught ReferenceError: __webpack_require__ is not defined`
`Uncaught (in promise) TypeError: c(...).Z is not a function`

The compiled code is missing `__webpack_require__`

**If the current behavior is a bug, please provide the steps to reproduce.**

Here's a very minimal setup that reproduces this bug.

```js
// webpack.config.js
const path = require("path");

module.exports = {
  entry: {
    app: "./src/app.js",
    home: {
      import: './src/home.js',
      dependOn: 'app' // removing this line fixes it
    }
  },
  output: {
    path: path.resolve("./dist"),
  },
  optimization: {
    runtimeChunk: "single",
  },
};
```

```js
// src/app.js
import("./test.js");
```

```js
// src/log.js
export default function (msg) {
  console.log(msg);
}
```

```js
// src/test.js
import log from "./log";
log("Hi");
```

```js
// src/home.js
import log from "./log";
log("Hi");
```

```html
<script src="runtime.js"></script>
<script src="app.js"></script>
<script src="home.js"></script>
```

**What is the expected behavior?**

This error should not happen, it was working without errors on 5.18.0

**Other relevant information:**
webpack version:  5.19.0
Node.js version: v15.7.0
Operating System: macOS 11.2
Additional tools:

**Comment by alexander-akait** [comment]
You forget to include `vendor` files, look at the files in `dist` directory, you ignore `How we can reproduce it`, so we can't provide which file you forgot to add

**Comment by alexander-akait** [comment]
in dev mode I have `4.js` file

**Comment by davidmerrique** [comment]
@alexander-akait 

Here is where this error is happening `Uncaught ReferenceError: __webpack_require__ is not defined`:
```js
// dist/home.js
(self.webpackChunkhmm = self.webpackChunkhmm || [
]).push([[177],
{
  666: (e, _, s) =>{
    'use strict';
    (0, s(151).Z) ('Hi')
  },
  151: () =>{
    'use strict';
    function e(e) {
      console.log(e)
    }
    __webpack_require__.d(__webpack_exports__, {
      Z: () =>e
    })
  }
},
0,
[
  [666,
  666,
  143]
]]);
```

And here is where this error is happening `Uncaught (in promise) TypeError: c(...).Z is not a function`:
```js
// dist/4.js
(self.webpackChunkhmm = self.webpackChunkhmm || [
]).push([[4],
{
  151: (s, e, c) =>{
    'use strict';
    function u(s) {
      console.log(s)
    }
    c.d(e, {
      Z: () =>u
    })
  },
  4: (s, e, c) =>{
    'use strict';
    c.r(e),
    (0, c(151).Z) ('Hi')
  }
}
]);
```

**Comment by alexander-akait** [comment]
```
<script src="./dist/runtime.js"></script>
<script src="./dist/src_test_js.js"></script>
<script src="./dist/app.js"></script>
<script src="./dist/home.js"></script>
```

**Comment by alexander-akait** [comment]
I recommend to use `HtmlWebpackPlugin` to avoid these errors in future

**Comment by davidmerrique** [comment]
@alexander-akait But what about in production? There is no `src_test_js.js` file and the error still occurs

**Comment by davidmerrique** [comment]
@alexander-akait Here's a repository that replicates the error. If webpack 5.18.0 is used, no error. 5.19.0 - error

https://github.com/davidmerrique/webpack-dependon-error

**Comment by alexander-akait** [comment]
I can't understand what do you want from webpack here, you don't include extracted chunk, so code will not work, because webpack fix some problems and better split chunks between entry points

**Comment by alexander-akait** [comment]
Again you use `HtmlWebpackPlugin` to auto generate `script` or disable `deterministic` chunk names using https://webpack.js.org/configuration/optimization/#optimizationchunkids in production, just use `named`

**Comment by davidmerrique** [comment]
@alexander-akait 

Here's the output of `home.js` in v5.18.0
```js
(self.webpackChunkhmm = self.webpackChunkhmm || []).push([
  [177],
  {
    666: (s, e, c) => {
      "use strict";
      (0, c(151).Z)("Hi");
    },
    151: (s, e, c) => {
      "use strict";
      function u(s) {
        console.log(s);
      }
      c.d(e, { Z: () => u });
    },
  },
  0,
  [[666, 666, 143]],
]);
```

Here it is with v5.19.0
```js
(self.webpackChunkhmm = self.webpackChunkhmm || []).push([
  [177],
  {
    666: (e, _, s) => {
      "use strict";
      (0, s(151).Z)("Hi");
    },
    151: () => {
      "use strict";
      function e(e) {
        console.log(e);
      }
      __webpack_require__.d(__webpack_exports__, { Z: () => e });
    },
  },
  0,
  [[666, 666, 143]],
]);
```

Nowhere in the generated code does `__webpack_require__` exist (neither does `__webpack_exports__`)

**Comment by alexander-akait** [comment]
> disable deterministic chunk names using https://webpack.js.org/configuration/optimization/#optimizationchunkids in production, just use named

`home` depend on `app`, so `test.js` can be reused between `home` and `app`, so you have `src_test_js.js`

**Comment by davidmerrique** [comment]
@alexander-akait disabling deterministic chunk names doesn't make any difference

With `5.18.0` I don't need to include the `<script src="./dist/src_test_js.js"></script>` tag, webpack loads it for me.
Why is it that I would need to include extra script tags with `5.19.0`?

There's clearly a breaking change in this minor release. 

In my previous comment, the built code is broken:
```js
// 5.18.0
    151: (s, e, c) => {
      "use strict";
      function u(s) {
        console.log(s);
      }
      c.d(e, { Z: () => u });
    },
```
```js
// 5.19.0
    151: () => {
      "use strict";
      function e(e) {
        console.log(e);
      }
      __webpack_require__.d(__webpack_exports__, { Z: () => e });
    },
```

**Comment by alexander-akait** [comment]
It is not breaking change, it is fix, because it was not working as expected, what is why you should generate `html` file from stats or using a plugin for this. You can found it in docs https://webpack.js.org/guides/output-management/

**Comment by davidmerrique** [comment]
@alexander-akait I included `HtmlWebpackPlugin` and I get the same error: https://github.com/davidmerrique/webpack-dependon-error/tree/html-webpack-plugin

It generates this:
```html
<script src="runtime.js"></script>
<script src="app.js"></script>
<script src="home.js"></script>
```

`Uncaught ReferenceError: __webpack_require__ is not defined`

**Comment by sokra** [comment]
When script tags are missing you won't get an error. It will just do nothing.

Here it seem to be a bug. Looks like a require requirement is missing...

**Comment by sokra** [comment]
fixed in https://github.com/webpack/webpack/releases/tag/v5.20.0

**Comment by davidmerrique** [comment]
@sokra Thanks so much!

**Comment by alexander-akait** [comment]
@davidmerrique sorry, it was my mistake, but we investigate it deeply and found a bug
