### ISSUE TITLE
5.95.0 -> 5.96.1 regression TypeError: this._moduleGraph.getIncomingConnections is not a function

### ISSUE THREAD

**Issue by Knagis** [webpack/webpack#18954]
# Bug report

**What is the current behavior?**

After upgrading webpack from 5.95.0 to 5.96.1, running webpack production build results in 

```typescript
TypeError: this._moduleGraph.getIncomingConnections is not a function
    at AssetGenerator.getTypes (/builds/mobile/js-clients/node_modules/webpack/lib/asset/AssetGenerator.js:593:41)
    at NormalModule.getSourceTypes (/builds/mobile/js-clients/node_modules/webpack/lib/NormalModule.js:1386:66)
    at getSize (/builds/mobile/js-clients/node_modules/webpack/lib/optimize/SplitChunksPlugin.js:1717:34)
    at /builds/mobile/js-clients/node_modules/webpack/lib/util/deterministicGrouping.js:295:40
    at Function.from (<anonymous>)
    at module.exports (/builds/mobile/js-clients/node_modules/webpack/lib/util/deterministicGrouping.js:293:22)
    at /builds/mobile/js-clients/node_modules/webpack/lib/optimize/SplitChunksPlugin.js:1689:23
    at Hook.eval (eval at create (/builds/mobile/js-clients/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:19:16)
    at Hook.CALL_DELEGATE [as _call] (/builds/mobile/js-clients/node_modules/tapable/lib/Hook.js:14:14)
    at Compilation.seal (/builds/mobile/js-clients/node_modules/webpack/lib/Compilation.js:3111:36)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

This happens on our rather large monorepo build, i haven't had the chance to troubleshoot, hoping that the stack trace might give enough idea to you. If not, i will do more research in the upcoming days.

**What is the expected behavior?**

**Other relevant information:**
webpack version:  5.96.1
Node.js version:  20.11.1
Operating System:  linux/docker
Additional tools:
