### ISSUE TITLE
google-fonts-webpack-plugin@0.4.4 not working in webpack@4.1.1

### ISSUE THREAD

**Issue by swichelecki** [webpack/webpack#7040]
**Do you want to request a  or report a *bug*?**
Bug

**What is the current behavior?**

When I try to use `google-fonts-webpack-plugin@0.4.4` with `webpack@4.1.1` and `html-webpack-plugin@3.0.6` I am getting the following errors and the code won't compile:

`(node:73383) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead`

```
ERROR in   TypeError: cb is not a function
  
  - index.js:116 compilation.plugin
    [site]/[google-fonts-webpack-plugin]/src/index.js:116:5
  
  - Hook.js:35 AsyncSeriesWaterfallHook.lazyCompileHook [as _promise]
    [site]/[tapable]/lib/Hook.js:35:21
  
  - index.js:647 
    [site]/[html-webpack-plugin]/index.js:647:47
  
  - index.js:162 Promise.resolve.then.then.then.then.compilationResult
    [site]/[html-webpack-plugin]/index.js:162:36
```

**If the current behavior is a bug, please provide the steps to reproduce.**

In `webpack.config`:

`var GoogleFontsPlugin = require('google-fonts-webpack-plugin');`

```
new GoogleFontsPlugin({
            fonts: [{
              family: 'Open Sans',
              variants: ['400']
            },
            {
              family: 'Ubuntu',
              variants: ['500', '400', '300']
            }]
      })
```

**What is the expected behavior?**

I have used similar code in webpack v3 and was easily able to use Google fonts.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
I am not a webpack pro, so if it's my mistake I apologize in advance.

**Comment by ooflorent** [comment]
The issue should be opened on the plugin repository.
