### ISSUE TITLE
webpack 4.8.1 error

### ISSUE THREAD

**Issue by Muhanady** [webpack/webpack#7322]
# Bug report

**What is the current behavior?**
After updating the webpack from 2.5.1 to 4.81 i start to have the error below

> PS C:\Users\pc\Desktop\mmm> webpack --config .\webpack.config.js
> (node:16372) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
> (node:16372) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
> TypeError: dep.getResourceIdentifier is not a function
>     at addDependency (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:403:30)
>     at iterationOfArrayCallback (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:88:3)
>     at addDependenciesBlock (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:423:5)
>     at Compilation.processModuleDependencies (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:434:4)
>     at afterBuild (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:556:15)
>     at buildModule.err (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:600:11)
>     at callback (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:358:35)
>     at module.build.error (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:394:12)
>     at DelegatedModule.build (C:\Users\pc\Desktop\mmm\node_modules\webpack\lib\DelegatedModule.js:45:3)
>     at Compilation.buildModule (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:362:10)
>     at factory.create (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:583:14)
>     at factory (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\lib\NormalModuleFactory.js:366:6)
>     at hooks.afterResolve.callAsync (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\lib\NormalModuleFactory.js:143:13)
>     at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
>     at resolver (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\lib\NormalModuleFactory.js:126:29)
>     at process.nextTick (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\lib\NormalModuleFactory.js:304:9)
>     at _combinedTickCallback (internal/process/next_tick.js:131:7)
>     at process._tickCallback (internal/process/next_tick.js:180:9)

**If the current behavior is a bug, please provide the steps to reproduce.**
if i update the webğack and run --config command i receive the error

**What is the expected behavior?**

**Other relevant information:**

```
Angular CLI: 6.0.0
Node: 8.11.1
OS: win32 x64
Angular: 4.2.5
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router, tsc-wrapped

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.0 (cli-only)
@angular-devkit/core         0.6.0 (cli-only)
@angular-devkit/schematics   0.6.0 (cli-only)
@ngtools/webpack             1.5.0
@schematics/angular          0.6.0 (cli-only)
@schematics/update           0.6.0 (cli-only)
rxjs                         5.4.2
typescript                   2.4.1
webpack                      2.5.1
```

**Comment by evilebottnawi** [comment]
@Muhanady please provide your configuration, looks you have plugin what incompatibility with `webpack@4`

**Comment by Muhanady** [comment]
Actually an not a professional. How I can know which one is incompatible. Am not able to run my project any help is appreciated

**Comment by evilebottnawi** [comment]
@Muhanady `yarn/npm install` should report about incompatibility, also you can enable/disable loaders/plugins step by step, also configuration will help solve problem fastly

**Comment by Muhanady** [comment]
@evilebottnawi thank you. i did find what pack is incompatible with webpack 4.8.1. the project run well now but still not able to run webpack config. here is the error
`webpack --config .\webpack.config.vendor.js
TypeError: dep.getResourceIdentifier is not a function
    at addDependency (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:403:30)
    at iterationOfArrayCallback (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:88:3)
    at addDependenciesBlock (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:423:5)
    at Compilation.processModuleDependencies (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:434:4)
    at afterBuild (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:695:13)
    at buildModule.err (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:723:8)
    at callback (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:358:35)
    at module.build.error (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:394:12)
    at DllModule.build (D:\CarSale\node_modules\webpack\lib\DllModule.js:36:10)
    at Compilation.buildModule (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:362:10)
    at moduleFactory.create (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:711:12)
    at DllModuleFactory.create (D:\CarSale\node_modules\webpack\lib\DllModuleFactory.js:16:3)
    at semaphore.acquire (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:658:18)
    at Semaphore.acquire (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\lib\util\Semaphore.js:17:4)
    at Compilation._addModuleChain (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:657:18)
    at Compilation.addEntry (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:741:8)
    at compiler.plugin (D:\CarSale\node_modules\webpack\lib\DllEntryPlugin.js:28:16)
    at AsyncParallelHook.eval [as callAsync] (eval at create (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:24:12),
<anonymous>:7:1)
    at AsyncParallelHook.lazyCompileHook [as _callAsync] (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\node_modules\tapable\lib\Hook.js:35:21)
    at hooks.beforeCompile.callAsync.err (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\lib\Compiler.js:476:20)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\node_modules\tapable\lib\Hook.js:35:21)
    at Compiler.compile (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\lib\Compiler.js:469:28)
    at readRecords.err (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\lib\Compiler.js:220:11)
    at Compiler.readRecords (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\lib\Compiler.js:342:11)
    at hooks.run.callAsync.err (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\lib\Compiler.js:217:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\node_modules\tapable\lib\Hook.js:35:21)
    at hooks.beforeRun.callAsync.err (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\lib\Compiler.js:214:19)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\node_modules\tapable\lib\Hook.js:35:21)
    at Compiler.run (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\lib\Compiler.js:211:24)
    at runWithDependencies (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\lib\MultiCompiler.js:251:15)
    at asyncLib.map (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\lib\MultiCompiler.js:175:6)
    at arrayEachIndex (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\node_modules\neo-async\async.js:2539:9)
    at Object.map (C:\Users\pc\AppData\Roaming\npm\node_modules\webpack\node_modules\neo-async\async.js:2890:9)`

**Comment by evilebottnawi** [comment]
@Muhanady sorry without minimum reproducible test repo, i can't help (any can't help)

**Comment by Muhanady** [comment]
here is my configuration 
`{
  "name": "CarSale",
  "private": true,
  "version": "0.0.0",
  "scripts": {
    "test": "karma start ClientApp/test/karma.conf.js"
  },
  "devDependencies": {
    "@angular/animations": "4.2.5",
    "@angular/common": "4.2.5",
    "@angular/compiler": "4.2.5",
    "@angular/compiler-cli": "4.2.5",
    "@angular/core": "4.2.5",
    "@angular/forms": "4.2.5",
    "@angular/http": "4.2.5",
    "@angular/platform-browser": "4.2.5",
    "@angular/platform-browser-dynamic": "4.2.5",
    "@angular/platform-server": "4.2.5",
    "@angular/router": "4.2.5",
    "@ngtools/webpack": "1.5.0",
    "@types/chai": "4.0.1",
    "@types/jasmine": "2.5.53",
    "@types/webpack-env": "1.13.0",
    "angular2-router-loader": "0.3.5",
    "angular2-template-loader": "0.6.2",
    "aspnet-prerendering": "^3.0.1",
    "aspnet-webpack": "^2.0.1",
    "awesome-typescript-loader": "3.2.1",
    "bootstrap": "3.3.7",
    "chai": "4.0.2",
    "css": "2.2.1",
    "css-loader": "0.28.4",
    "es6-shim": "0.35.3",
    "event-source-polyfill": "0.0.9",
    "expose-loader": "0.7.3",
    "extract-text-webpack-plugin": "2.1.2",
    "file-loader": "0.11.2",
    "html-loader": "0.4.5",
    "isomorphic-fetch": "2.2.1",
    "jasmine-core": "2.6.4",
    "jquery": "3.2.1",
    "json-loader": "0.5.4",
    "karma": "1.7.0",
    "karma-chai": "0.1.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-jasmine": "1.1.0",
    "karma-webpack": "2.0.3",
    "preboot": "4.5.2",
    "raw-loader": "0.5.1",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.4.2",
    "style-loader": "0.18.2",
    "to-string-loader": "1.1.5",
    "typescript": "2.4.1",
    "url-loader": "0.5.9",
    "webpack": "^2.5.1",
    "webpack-hot-middleware": "2.18.2",
    "webpack-merge": "4.1.0",
    "zone.js": "0.8.12"
  },
  "dependencies": {}
}
`
@evilebottnawi i just created a new project with 
1 `dotnet new angular` command and after that
2. `npm install  `
3. `npm install webpack@latest`
4. webpack <---- the exception comes here

**Comment by evilebottnawi** [comment]
@Muhanady you have very old dependencies in `package.json` (a lot of their incompatibility with `webpack@4`). Run `npm outdate`/`yarn outdated` and upgrade your dependencies to latest versions

**Comment by Muhanady** [comment]
@evilebottnawi i did update them all as you said; (thanks) but now am having anther issue 
`PS D:\CarSale> webpack
Hash: 6aa760b2df9350cb563c4da7775821a60bd816f1
Version: webpack 4.8.3
Child
    Hash: 6aa760b2df9350cb563c
    Time: 24054ms
    Built at: 2018-05-16 22:56:38
     1 asset
    Entrypoint main-client = main-client.js

    WARNING in ./node_modules/@angular/core/fesm5/core.js
    5560:15-36 Critical dependency: the request of a dependency is an expression
     @ ./node_modules/@angular/core/fesm5/core.js
     @ ./ClientApp/boot.browser.ts

    WARNING in ./node_modules/@angular/core/fesm5/core.js
    5572:15-102 Critical dependency: the request of a dependency is an expression
     @ ./node_modules/@angular/core/fesm5/core.js
     @ ./ClientApp/boot.browser.ts

    WARNING in ./node_modules/@angular/core/fesm5/core.js
    System.import() is deprecated and will be removed soon. Use import() instead.
    For more info visit https://webpack.js.org/guides/code-splitting/
     @ ./ClientApp/boot.browser.ts 5560:15-36 4:0-47 18:4-18

    WARNING in ./node_modules/@angular/core/fesm5/core.js
    System.import() is deprecated and will be removed soon. Use import() instead.
    For more info visit https://webpack.js.org/guides/code-splitting/
     @ ./ClientApp/boot.browser.ts 5572:15-102 4:0-47 18:4-18

    WARNING in configuration
    The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
    You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

    ERROR in ./node_modules/bootstrap/dist/js/bootstrap.js
    Module not found: Error: Can't resolve 'popper.js' in 'D:\CarSale\node_modules\bootstrap\dist\js'     @ ./node_modules/bootstrap/dist/js/bootstrap.js 7:101-121
     @ ./ClientApp/boot.browser.ts

    ERROR in ./node_modules/rxjs/add/operator/map.js
    Module not found: Error: Can't resolve 'rxjs-compat/add/operator/map' in 'D:\CarSale\node_modules\rxjs\add\operator'
     @ ./node_modules/rxjs/add/operator/map.js 3:0-39
     @ ./ClientApp/app/services/make.service.ts
     @ ./ClientApp/app/app.shared.module.ts
     @ ./ClientApp/app/app.browser.module.ts
     @ ./ClientApp/boot.browser.ts

    ERROR in [at-loader] ./ClientApp/app/services/make.service.ts:11:40
        TS2339: Property 'map' does not exist on type 'Observable<Response>'.

    ERROR in [at-loader] ./ClientApp/app/services/make.service.ts:11:44
        TS7006: Parameter 'm' implicitly has an 'any' type.

    ERROR in [at-loader] ./ClientApp/app/services/vehicle.service.ts:12:40
        TS2339: Property 'map' does not exist on type 'Observable<Response>'.

    ERROR in [at-loader] ./ClientApp/app/services/vehicle.service.ts:12:44
        TS7006: Parameter 'm' implicitly has an 'any' type.

    ERROR in [at-loader] ./ClientApp/app/services/vehicle.service.ts:16:43
        TS2339: Property 'map' does not exist on type 'Observable<Response>'.

    ERROR in [at-loader] ./ClientApp/app/services/vehicle.service.ts:16:47
        TS7006: Parameter 'm' implicitly has an 'any' type.

    ERROR in [at-loader] ./ClientApp/app/services/vehicle.service.ts:20:52
        TS2339: Property 'map' does not exist on type 'Observable<Response>'.

    ERROR in [at-loader] ./ClientApp/app/services/vehicle.service.ts:20:56
        TS7006: Parameter 'm' implicitly has an 'any' type.

    ERROR in [at-loader] ./ClientApp/app/components/fetchdata/fetchdata.component.ts:9:12
        TS2564: Property 'forecasts' has no initializer and is not definitely assigned in the constructor.

    ERROR in [at-loader] ./ClientApp/app/components/vehicle-form/vehicle-form.component.ts:11:3
        TS2564: Property 'makes' has no initializer and is not definitely assigned in the constructor.

    ERROR in [at-loader] ./ClientApp/app/components/vehicle-form/vehicle-form.component.ts:12:3
        TS2564: Property 'models' has no initializer and is not definitely assigned in the constructor.

    ERROR in [at-loader] ./ClientApp/app/components/vehicle-form/vehicle-form.component.ts:17:3
        TS2564: Property 'features' has no initializer and is not definitely assigned in the constructor.

    ERROR in [at-loader] ./ClientApp/app/components/vehicle-form/vehicle-form.component.ts:21:46
        TS7006: Parameter 'm' implicitly has an 'any' type.

    ERROR in [at-loader] ./ClientApp/app/components/vehicle-form/vehicle-form.component.ts:22:49
        TS7006: Parameter 'f' implicitly has an 'any' type.

    ERROR in [at-loader] ./ClientApp/app/components/vehicle-form/vehicle-form.component.ts:40:56
        TS7006: Parameter 's' implicitly has an 'any' type.

    ERROR in [at-loader] ./ClientApp/boot.server.ts:26:29
        TS2339: Property 'first' does not exist on type 'Observable<boolean>'.

    ERROR in [at-loader] ./ClientApp/boot.server.ts:26:35
        TS7006: Parameter 'isStable' implicitly has an 'any' type.

    ERROR in [at-loader] ./ClientApp/app/services/feature.service.ts:11:42
        TS2339: Property 'map' does not exist on type 'Observable<Response>'.

    ERROR in [at-loader] ./ClientApp/app/services/feature.service.ts:11:46
        TS7006: Parameter 'm' implicitly has an 'any' type.
Child
    Hash: 4da7775821a60bd816f1
    Time: 23036ms
    Built at: 2018-05-16 22:56:37
     1 asset
    Entrypoint main-server = main-server.js

    WARNING in configuration
    The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
    You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

    ERROR in ./node_modules/rxjs/add/operator/first.js
    Module not found: Error: Can't resolve 'rxjs-compat/add/operator/first' in 'D:\CarSale\node_modules\rxjs\add\operator'
     @ ./node_modules/rxjs/add/operator/first.js 3:0-41
     @ ./ClientApp/boot.server.ts

    ERROR in ./node_modules/rxjs/add/operator/map.js
    Module not found: Error: Can't resolve 'rxjs-compat/add/operator/map' in 'D:\CarSale\node_modules\rxjs\add\operator'
     @ ./node_modules/rxjs/add/operator/map.js 3:0-39
     @ ./ClientApp/app/services/make.service.ts
     @ ./ClientApp/app/app.shared.module.ts
     @ ./ClientApp/app/app.server.module.ts
     @ ./ClientApp/boot.server.ts

    ERROR in [at-loader] ./ClientApp/app/services/make.service.ts:11:40
        TS2339: Property 'map' does not exist on type 'Observable<Response>'.

    ERROR in [at-loader] ./ClientApp/app/services/make.service.ts:11:44
        TS7006: Parameter 'm' implicitly has an 'any' type.

    ERROR in [at-loader] ./ClientApp/app/services/vehicle.service.ts:12:40
        TS2339: Property 'map' does not exist on type 'Observable<Response>'.

    ERROR in [at-loader] ./ClientApp/app/services/vehicle.service.ts:12:44
        TS7006: Parameter 'm' implicitly has an 'any' type.

    ERROR in [at-loader] ./ClientApp/app/services/vehicle.service.ts:16:43
        TS2339: Property 'map' does not exist on type 'Observable<Response>'.

    ERROR in [at-loader] ./ClientApp/app/services/vehicle.service.ts:16:47
        TS7006: Parameter 'm' implicitly has an 'any' type.

    ERROR in [at-loader] ./ClientApp/app/services/vehicle.service.ts:20:52
        TS2339: Property 'map' does not exist on type 'Observable<Response>'.

    ERROR in [at-loader] ./ClientApp/app/services/vehicle.service.ts:20:56
        TS7006: Parameter 'm' implicitly has an 'any' type.

    ERROR in [at-loader] ./ClientApp/app/components/fetchdata/fetchdata.component.ts:9:12
        TS2564: Property 'forecasts' has no initializer and is not definitely assigned in the constructor.

    ERROR in [at-loader] ./ClientApp/app/components/vehicle-form/vehicle-form.component.ts:11:3
        TS2564: Property 'makes' has no initializer and is not definitely assigned in the constructor.

    ERROR in [at-loader] ./ClientApp/app/components/vehicle-form/vehicle-form.component.ts:12:3
        TS2564: Property 'models' has no initializer and is not definitely assigned in the constructor.

    ERROR in [at-loader] ./ClientApp/app/components/vehicle-form/vehicle-form.component.ts:17:3
        TS2564: Property 'features' has no initializer and is not definitely assigned in the constructor.

    ERROR in [at-loader] ./ClientApp/app/components/vehicle-form/vehicle-form.component.ts:21:46
        TS7006: Parameter 'm' implicitly has an 'any' type.

    ERROR in [at-loader] ./ClientApp/app/components/vehicle-form/vehicle-form.component.ts:22:49
        TS7006: Parameter 'f' implicitly has an 'any' type.

    ERROR in [at-loader] ./ClientApp/app/components/vehicle-form/vehicle-form.component.ts:40:56
        TS7006: Parameter 's' implicitly has an 'any' type.

    ERROR in [at-loader] ./ClientApp/boot.server.ts:26:29
        TS2339: Property 'first' does not exist on type 'Observable<boolean>'.

    ERROR in [at-loader] ./ClientApp/boot.server.ts:26:35
        TS7006: Parameter 'isStable' implicitly has an 'any' type.

    ERROR in [at-loader] ./ClientApp/app/services/feature.service.ts:11:42
        TS2339: Property 'map' does not exist on type 'Observable<Response>'.

    ERROR in [at-loader] ./ClientApp/app/services/feature.service.ts:11:46
        TS7006: Parameter 'm' implicitly has an 'any' type.`

**Comment by evilebottnawi** [comment]
@Muhanady You have many difference problem here, better use https://github.com/angular/angular-cli for angular based projects (all works fine and documentated)

**Comment by Muhanady** [comment]
@evilebottnawi  thank you very much for you advice. am trying me best to clear them one by one and i hope that i can. i do not thank that it might be some thing related with angular-cli but i'll check that.

**Comment by Muhanady** [comment]
at the end i was able to make the project work. many updates and this blog did help me too 
[Blog](http://www.talkingdotnet.com/upgrade-angular-4-app-angular-5-visual-studio-2017/)
thanks every one
