### ISSUE TITLE
Module not found errors after upgrading from webpack 2.0.2-beta to 2.0.6-beta

### ISSUE THREAD

**Issue by Globegitter** [webpack/webpack#1968]
I have been playing around with webpack 2.0.2-beta and it has been working mostly fine. Now after upgrading to 2.0.6-beta (actually sine 2.0.4) I am getting some errors that are quite hard to identify what exactly the cause is:

```js
✘ Compilation failed with 3 errors

 multi main
Module not found: Error: Can't resolve 'babel?{"presets":["/home/mpadourek/Projects/core/plz-out/gen/third_party/js/babel-preset-es2015/index.js","/home/mpadourek/Projects/core/plz-out/gen/third_party/js/babel-preset-react/index.js"],"plugins":["/home/mpadourek/Projects/core/plz-out/gen/third_party/js/babel-plugin-transform-decorators-legacy/lib/index.js","/home/mpadourek/Projects/core/plz-out/gen/third_party/js/babel-plugin-syntax-trailing-function-commas/lib/index.js","/home/mpadourek/Projects/core/plz-out/gen/third_party/js/babel-plugin-transform-class-properties/lib/index.js","/home/mpadourek/Projects/core/plz-out/gen/third_party/js/babel-plugin-transform-object-rest-spread/lib/index.js","/home/mpadourek/Projects/core/plz-out/gen/third_party/js/babel-plugin-syntax-async-functions/lib/index.js","/home/mpadourek/Projects/core/plz-out/gen/third_party/js/babel-plugin-transform-regenerator/lib/index.js","/home/mpadourek/Projects/core/plz-out/gen/script/build_js/custom_babel_plugins/rootPath.js"],"sourceMaps":false}' in '/home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/graphiql/graphiql'
resolve 'babel?{"presets":["/home/mpadourek/Projects/core/plz-out/gen/third_party/js/babel-preset-es2015/index.js","/home/mpadourek/Projects/core/plz-out/gen/third_party/js/babel-preset-react/index.js"],"plugins":["/home/mpadourek/Projects/core/plz-out/gen/third_party/js/babel-plugin-transform-decorators-legacy/lib/index.js","/home/mpadourek/Projects/core/plz-out/gen/third_party/js/babel-plugin-syntax-trailing-function-commas/lib/index.js","/home/mpadourek/Projects/core/plz-out/gen/third_party/js/babel-plugin-transform-class-properties/lib/index.js","/home/mpadourek/Projects/core/plz-out/gen/third_party/js/babel-plugin-transform-object-rest-spread/lib/index.js","/home/mpadourek/Projects/core/plz-out/gen/third_party/js/babel-plugin-syntax-async-functions/lib/index.js","/home/mpadourek/Projects/core/plz-out/gen/third_party/js/babel-plugin-transform-regenerator/lib/index.js","/home/mpadourek/Projects/core/plz-out/gen/script/build_js/custom_babel_plugins/rootPath.js"],"sourceMaps":false}' in '/home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/graphiql/graphiql'
  Parsed request is a module
  No description file found
  resolve as module
    module variation babel-loader
      /home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/graphiql/graphiql/node_modules doesn't exist or is not a directory
      /home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/graphiql/node_modules doesn't exist or is not a directory
      /home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/node_modules doesn't exist or is not a directory
      /home/mpadourek/Projects/core/plz-out/tmp/revver/node_modules doesn't exist or is not a directory
      /home/mpadourek/Projects/core/plz-out/tmp/node_modules doesn't exist or is not a directory
      /home/mpadourek/Projects/core/plz-out/node_modules doesn't exist or is not a directory
      /home/mpadourek/Projects/core/node_modules doesn't exist or is not a directory
      /home/mpadourek/Projects/node_modules doesn't exist or is not a directory
      /home/mpadourek/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
    /home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/graphiql/graphiql/node_modules doesn't exist or is not a directory
    /home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/graphiql/node_modules doesn't exist or is not a directory
    /home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/node_modules doesn't exist or is not a directory
    /home/mpadourek/Projects/core/plz-out/tmp/revver/node_modules doesn't exist or is not a directory
    /home/mpadourek/Projects/core/plz-out/tmp/node_modules doesn't exist or is not a directory
    /home/mpadourek/Projects/core/plz-out/node_modules doesn't exist or is not a directory
    /home/mpadourek/Projects/core/node_modules doesn't exist or is not a directory
    /home/mpadourek/Projects/node_modules doesn't exist or is not a directory
    /home/mpadourek/node_modules doesn't exist or is not a directory
    /home/node_modules doesn't exist or is not a directory
    /node_modules doesn't exist or is not a directory
[/home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/graphiql/graphiql/package.json]
[/home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/graphiql/graphiql/node_modules]
[/home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/graphiql/graphiql/node_modules]
[/home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/graphiql/node_modules]
[/home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/graphiql/node_modules]
[/home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/node_modules]
[/home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/node_modules]
[/home/mpadourek/Projects/core/plz-out/tmp/revver/node_modules]
[/home/mpadourek/Projects/core/plz-out/tmp/revver/node_modules]
[/home/mpadourek/Projects/core/plz-out/tmp/node_modules]
[/home/mpadourek/Projects/core/plz-out/tmp/node_modules]
[/home/mpadourek/Projects/core/plz-out/node_modules]
[/home/mpadourek/Projects/core/plz-out/node_modules]
[/home/mpadourek/Projects/core/node_modules]
[/home/mpadourek/Projects/core/node_modules]
[/home/mpadourek/Projects/node_modules]
[/home/mpadourek/Projects/node_modules]
[/home/mpadourek/node_modules]
[/home/mpadourek/node_modules]
[/home/node_modules]
[/home/node_modules]
[/node_modules]
[/node_modules]
 @ multi main
 multi main
Module not found: Error: Can't resolve 'imports?define=>false' in '/home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/graphiql/graphiql'
resolve 'imports?define=>false' in '/home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/graphiql/graphiql'
  Parsed request is a module
  No description file found
  resolve as module
    module variation imports-loader
      /home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/graphiql/graphiql/node_modules doesn't exist or is not a directory
      /home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/graphiql/node_modules doesn't exist or is not a directory
      /home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/node_modules doesn't exist or is not a directory
      /home/mpadourek/Projects/core/plz-out/tmp/revver/node_modules doesn't exist or is not a directory
      /home/mpadourek/Projects/core/plz-out/tmp/node_modules doesn't exist or is not a directory
      /home/mpadourek/Projects/core/plz-out/node_modules doesn't exist or is not a directory
      /home/mpadourek/Projects/core/node_modules doesn't exist or is not a directory
      /home/mpadourek/Projects/node_modules doesn't exist or is not a directory
      /home/mpadourek/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
    /home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/graphiql/graphiql/node_modules doesn't exist or is not a directory
    /home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/graphiql/node_modules doesn't exist or is not a directory
    /home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/node_modules doesn't exist or is not a directory
    /home/mpadourek/Projects/core/plz-out/tmp/revver/node_modules doesn't exist or is not a directory
    /home/mpadourek/Projects/core/plz-out/tmp/node_modules doesn't exist or is not a directory
    /home/mpadourek/Projects/core/plz-out/node_modules doesn't exist or is not a directory
    /home/mpadourek/Projects/core/node_modules doesn't exist or is not a directory
    /home/mpadourek/Projects/node_modules doesn't exist or is not a directory
    /home/mpadourek/node_modules doesn't exist or is not a directory
    /home/node_modules doesn't exist or is not a directory
    /node_modules doesn't exist or is not a directory
[/home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/graphiql/graphiql/package.json]
[/home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/graphiql/graphiql/node_modules]
[/home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/graphiql/graphiql/node_modules]
[/home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/graphiql/node_modules]
[/home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/graphiql/node_modules]
[/home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/node_modules]
[/home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/node_modules]
[/home/mpadourek/Projects/core/plz-out/tmp/revver/node_modules]
[/home/mpadourek/Projects/core/plz-out/tmp/revver/node_modules]
[/home/mpadourek/Projects/core/plz-out/tmp/node_modules]
[/home/mpadourek/Projects/core/plz-out/tmp/node_modules]
[/home/mpadourek/Projects/core/plz-out/node_modules]
[/home/mpadourek/Projects/core/plz-out/node_modules]
[/home/mpadourek/Projects/core/node_modules]
[/home/mpadourek/Projects/core/node_modules]
[/home/mpadourek/Projects/node_modules]
[/home/mpadourek/Projects/node_modules]
[/home/mpadourek/node_modules]
[/home/mpadourek/node_modules]
[/home/node_modules]
[/home/node_modules]
[/node_modules]
[/node_modules]
 @ multi main
 multi main
Module not found: Error: Can't resolve 'imports?define=>false' in '/home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/graphiql/graphiql'
resolve 'imports?define=>false' in '/home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/graphiql/graphiql'
  Parsed request is a module
  No description file found
  resolve as module
    module variation imports-loader
      /home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/graphiql/graphiql/node_modules doesn't exist or is not a directory
      /home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/graphiql/node_modules doesn't exist or is not a directory
      /home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/node_modules doesn't exist or is not a directory
      /home/mpadourek/Projects/core/plz-out/tmp/revver/node_modules doesn't exist or is not a directory
      /home/mpadourek/Projects/core/plz-out/tmp/node_modules doesn't exist or is not a directory
      /home/mpadourek/Projects/core/plz-out/node_modules doesn't exist or is not a directory
      /home/mpadourek/Projects/core/node_modules doesn't exist or is not a directory
      /home/mpadourek/Projects/node_modules doesn't exist or is not a directory
      /home/mpadourek/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
    /home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/graphiql/graphiql/node_modules doesn't exist or is not a directory
    /home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/graphiql/node_modules doesn't exist or is not a directory
    /home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/node_modules doesn't exist or is not a directory
    /home/mpadourek/Projects/core/plz-out/tmp/revver/node_modules doesn't exist or is not a directory
    /home/mpadourek/Projects/core/plz-out/tmp/node_modules doesn't exist or is not a directory
    /home/mpadourek/Projects/core/plz-out/node_modules doesn't exist or is not a directory
    /home/mpadourek/Projects/core/node_modules doesn't exist or is not a directory
    /home/mpadourek/Projects/node_modules doesn't exist or is not a directory
    /home/mpadourek/node_modules doesn't exist or is not a directory
    /home/node_modules doesn't exist or is not a directory
    /node_modules doesn't exist or is not a directory
[/home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/graphiql/graphiql/package.json]
[/home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/graphiql/graphiql/node_modules]
[/home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/graphiql/node_modules]
[/home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/node_modules]
[/home/mpadourek/Projects/core/plz-out/tmp/revver/node_modules]
[/home/mpadourek/Projects/core/plz-out/tmp/node_modules]
[/home/mpadourek/Projects/core/plz-out/node_modules]
[/home/mpadourek/Projects/core/node_modules]
[/home/mpadourek/Projects/node_modules]
[/home/mpadourek/node_modules]
[/home/node_modules]
[/node_modules]
[/home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/graphiql/graphiql/node_modules]
[/home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/graphiql/node_modules]
[/home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/node_modules]
[/home/mpadourek/Projects/core/plz-out/tmp/revver/node_modules]
[/home/mpadourek/Projects/core/plz-out/tmp/node_modules]
[/home/mpadourek/Projects/core/plz-out/node_modules]
[/home/mpadourek/Projects/core/node_modules]
[/home/mpadourek/Projects/node_modules]
[/home/mpadourek/node_modules]
[/home/node_modules]
[/node_modules]
 @ multi main
/home/mpadourek/Projects/core/plz-out/gen/script/build_js/index.js:29
    throw error;
    ^

Error
    at /home/mpadourek/Projects/core/plz-out/gen/script/build_js/index.js:27:19
    at Compiler.<anonymous> (/home/mpadourek/Projects/core/plz-out/gen/third_party/js/webpack/lib/Compiler.js:223:14)
    at Compiler.emitRecords (/home/mpadourek/Projects/core/plz-out/gen/third_party/js/webpack/lib/Compiler.js:311:37)
    at Compiler.<anonymous> (/home/mpadourek/Projects/core/plz-out/gen/third_party/js/webpack/lib/Compiler.js:216:11)
    at /home/mpadourek/Projects/core/plz-out/gen/third_party/js/webpack/lib/Compiler.js:304:11
    at Compiler.applyPluginsAsync (/home/mpadourek/Projects/core/plz-out/gen/third_party/js/webpack/node_modules/tapable/lib/Tapable.js:73:70)
    at Compiler.afterEmit (/home/mpadourek/Projects/core/plz-out/gen/third_party/js/webpack/lib/Compiler.js:301:8)
    at Compiler.<anonymous> (/home/mpadourek/Projects/core/plz-out/gen/third_party/js/webpack/lib/Compiler.js:296:14)
    at /home/mpadourek/Projects/core/plz-out/gen/third_party/js/webpack/node_modules/async/lib/async.js:52:16
    at done (/home/mpadourek/Projects/core/plz-out/gen/third_party/js/webpack/node_modules/async/lib/async.js:246:17)
```

We are using a non-standard build system (well, non-standard for nodejs and npm), so I am sure the issue has to do with that, but what changed between 2.0.2-beta and 2.0.4-beta for it to fail now?

**Comment by sokra** [comment]
The resolving option changed: https://gist.github.com/sokra/27b24881210b56bbaff7#resolving-options

**Comment by Globegitter** [comment]
Ok, just changed in our config

```js
 resolve: {
      root: RESOLVE_PATH
}
```
to
```js
 resolve: {
      modules: RESOLVE_PATH
}
```

It resolved the first error but now getting:

```js
 
✘ Compilation failed with 1 errors

 ./revver/frontend/graphiql/index.js
Module parse failed: /home/mpadourek/Projects/core/plz-out/gen/third_party/js/babel-loader/index.js?{"presets":["/home/mpadourek/Projects/core/plz-out/gen/third_party/js/babel-preset-es2015-webpack/index.js","/home/mpadourek/Projects/core/plz-out/gen/third_party/js/babel-preset-react/index.js"],"plugins":["/home/mpadourek/Projects/core/plz-out/gen/third_party/js/babel-plugin-transform-decorators-legacy/lib/index.js","/home/mpadourek/Projects/core/plz-out/gen/third_party/js/babel-plugin-syntax-trailing-function-commas/lib/index.js","/home/mpadourek/Projects/core/plz-out/gen/third_party/js/babel-plugin-transform-class-properties/lib/index.js","/home/mpadourek/Projects/core/plz-out/gen/third_party/js/babel-plugin-transform-object-rest-spread/lib/index.js","/home/mpadourek/Projects/core/plz-out/gen/third_party/js/babel-plugin-syntax-async-functions/lib/index.js","/home/mpadourek/Projects/core/plz-out/gen/third_party/js/babel-plugin-transform-regenerator/lib/index.js","/home/mpadourek/Projects/core/plz-out/gen/script/build_js/custom_babel_plugins/rootPath.js"],"sourceMaps":false}!/home/mpadourek/Projects/core/plz-out/tmp/revver/frontend/graphiql/graphiql/revver/frontend/graphiql/index.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import React from 'react';
| import ReactDOM from 'react-dom';
| import GraphiQL from 'graphiql';
 @ multi main
/home/mpadourek/Projects/core/plz-out/gen/script/build_js/index.js:29
    throw error;
    ^

Error: 
```

These are the loaders we have defined:
```js
    module: {
      preLoaders: [
        {test: /\.json$/, exclude: /node_modules/, loader: 'json'},
        {test: /\.glsl$/, loader: 'shader'}
      ],
      loaders: [
        {
          test: /\.(js|jsx)?$/,
          exclude: /(third_party|node_modules)/,
          loader: 'babel-loader',
          query: {
            presets: [
              require.resolve('babel-preset-es2015-webpack'),
              require.resolve('babel-preset-react')
            ],
            plugins: [
              require.resolve('babel-plugin-transform-decorators-legacy'),
              require.resolve('babel-plugin-syntax-trailing-function-commas'),
              require.resolve('babel-plugin-transform-class-properties'),
              require.resolve('babel-plugin-transform-object-rest-spread'),
              require.resolve('babel-plugin-syntax-async-functions'),
              require.resolve('babel-plugin-transform-regenerator'),
              path.resolve(PLUGIN_DIR, 'rootPath.js')
            ],
            sourceMaps: false
        }
      },
      {test: /\.(png|woff|woff2|eot|ttf|svg)$/, loader: 'url-loader?limit=100000'},
      sassLoader,
      // we tell webpack to ignore AMD so we don't have to write rules to replace the paths of these too
      // As some third party libs try AMD before require
      {test: /\.(js|jsx)?$/, loader: 'imports?define=>false'}
    ]
  },
```

I also tried playing around with it changing a few of our settings and adding `alias` to the `resolve` option but nothing seems to change anything. The changelog is really nice to have but can't quite tell just based on that and the error message what exactly is wrong/how to add an approriate loader. Is the issue that it has trouble finding the npm packages? Or do they need its own loader?

**Comment by dschissler** [comment]
I'm trying 2.0.7 and I also can't get Babel 5 or 6 to work.  The fairly recent `require.resolve` "fix" might be the problem.

**Comment by bebraw** [comment]
@Globegitter @dschissler Is this relevant still?

**Comment by dschissler** [comment]
Probably not although I am still unable to run Webpack 2 due to not knowing the new way to setup the text extractor.  I vote not relevant and I can make some noise later if it is.

**Comment by bebraw** [comment]
Ok, that will work. Thanks.

**Comment by Petercopter** [comment]
If you come across this while troubleshooting like me, keep in mind that `modules` is an array.
```
modules: [RESOLVE_PATH]
```
