### ISSUE TITLE
Webpack@3.2.0 Cannot find module 'enhanced-resolve'

### ISSUE THREAD

**Issue by SoaresMG** [webpack/webpack#5275]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Running webpack throws the following error after updating to 3.2.0

> Cannot find module 'enhanced-resolve'

After installing this package no error was thrown.

**If the current behavior is a bug, please provide the steps to reproduce.**
Running a project with Webpack@3.2.0 without package `enhanced-resolve`.

**What is the expected behavior?**
`enhanced-resolve` being set as a dependency by webpack (? maybe)

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Webpack@3.2.0
OS@Windows 10

**Comment by TheLarkInn** [comment]
Thank for you for the report.

**Comment by SoaresMG** [comment]
Hmmm strange, I removed the package to try one more time, and now it's working. Does npm cache packages or is this black magic?

**Comment by TheLarkInn** [comment]
Could be a possibility!!!

**Comment by sokra** [comment]
It's a dependency. Looks like some weird npm behavior...
