### ISSUE TITLE
[5.100.0] Typescript error: Cannot find name 'Float16Array'.

### ISSUE THREAD

**Issue by jlowcs** [webpack/webpack#19679]
# Bug report

When bumping from 5.99.9 to 5.100.0, the following TS type check error appears:
```
Cannot find name 'Float16Array'.
```

<img width="649" height="282" alt="Image" src="https://github.com/user-attachments/assets/f8b4326f-d2f9-44c4-94b3-e41a97b7b3d1" />

It is indeed missing from [@types/node](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/v22/compatibility/indexable.d.ts).

**What is the expected behavior?**

There should not be a typecheck error.

**Other relevant information:**
webpack version:  5.100.0
Node.js version: 22
Operating System: N/A
Additional tools: N/A

**Comment by alexander-akait** [comment]
Please update `@types/node`, we can't fix it on our side, it is a new type for Node.js, feel free to feedback

**Comment by alexander-akait** [comment]
Fixed - https://github.com/webpack/webpack/releases/tag/v5.100.1
