### ISSUE TITLE
Symlinks in project - loader not working when using include?

### ISSUE THREAD

**Issue by elado** [webpack/webpack#1643]
Can webpack read through symlinks? I have a simple symlink under `/src` with `.jsx` files. I have `{ test: /\.jsx?$/, loader: 'babel-loader?...', include: path.resolve(__dirname, 'src') }` but it won't load files with `babel-loader`, I get ES5 compilation error.

If I replace the symlink with the actual folder and files - it works.
If I replace the `include` with `exclude: /node_modules/` it also works.

Bug, or am I doing it wrong?

**Comment by gregvenech** [comment]
Having a similar issue with symlinks... I have all my modules under a `/src` folder in the root. Inside that `/src` folder I created a symlink to a directory `/globals` which is outside the root. Importing modules through the symlink works fine, however the loaders (in this case babel) don't transform these modules properly which causes:

`1:61  error  Parsing error: Illegal export declaration`
`...`
`You may need an appropriate loader to handle this file type.`

Tried a few things in the config such adding the actual path of the symlink to `resolveLoader.modulesDirectories` and in `loader.include`.

[This](https://github.com/webpack/webpack/issues/784) issue seems similar but none of the solutions there worked solved the issue.

**Comment by gregvenech** [comment]
Seems like adding this should solve the issue:

`resolveLoader: { root: path.join(__dirname, "node_modules") }`

so that the loaders are found even when not all modules exist inside the root containing the node_modules and webpack config:

> IMPORTANT: The loaders here are resolved relative to the resource which they are applied to. This means they are not resolved relative the the configuration file. If you have loaders installed from npm and your node_modules folder is not in a parent folder of all source files, webpack cannot find the loader. You need to add the node_modules folder as absolute path to the resolveLoader.root option. (resolveLoader: { root: path.join(__dirname, "node_modules") })

However, this didn't work for me :(

**Comment by gregvenech** [comment]
Seems to be an issue in the babel-loader (or my understanding of webpack and babel)... but I found another  [issue](https://github.com/babel/babel-loader/issues/179) there that seems to be more appropriate.

My style, css, and scss loaders all read through the symlink fine once I added the resolveLoader line mentioned above. It looks like the placement of .babelrc (or wherever you tell babel to allows modules) is the actual root cause. Sorry for blowing up this thread!

**Comment by arunabha** [comment]
+1, I have this exact problem, the loader (babel) does not seem to be getting applied to files under a symlink. Replacing the symlink with an actual directory works.

**Comment by s-panferov** [comment]
I think that the main issue here is that webpack resolves symlinks and it actually 'sees' this files by their absolute url. And this *absolute* path doesn't match your `include` directive or `test` regexp.

Could you please check this?

**Comment by s-panferov** [comment]
Some info about this behavior can be found here https://github.com/webpack/webpack/issues/554

**Comment by jraede** [comment]
I was able to fix this by doing the following in webpack.config.js (this is for importing our components library using the jsx files rather than the compiled umd):

```javascript
var includePaths = [
  fs.realpathSync(__dirname + '/app'),
  fs.realpathSync(__dirname + '/node_modules/my-repo/lib'),
];
```

And then later:
```javascript
module: {
    loaders: [{
      test: /\.js?$/,
      include: includePaths,
      loader: 'babel'
    }, {
      test: /\.jsx?$/,
      include: includePaths,
      loader: 'babel'
    },{
      test: /\.json?$/,
      loader: 'json'
    }, {
      test: /\.css$/,
      loader: 'style!css?modules&localIdentName=[name]---[local]---[hash:base64:5]'
    }]
  },
```

**Comment by eagsalazar** [comment]
I got this to work by setting the includePaths but also by setting both resolve.root and resolveLoader.root to `path.resolve(__dirname, 'node_modules')` (or wherever you want those external sources to be able to resolve modules).   @jraede I think that worked for you only because your include paths both had node_modules in an ancestor directory.   You need to set both so files external to your project that you want to import can themselves (a) import other modules from your project's node_modules, and (b) so your loaders can be resolved (otherwise you get cannot resolve module 'babel', etc).

**Comment by BarukhOr** [comment]
@jraede would it be possible for you to provide your webpack.config I'm running into a similar problem and even after implementing your suggested solution i get the following error 
```
ERROR in multi main
Module not found: Error: Cannot resolve 'file' or 'directory' /LifeInYourWay/iGem/src/index in /home/utibe/Desktop/GroundControl
 @ multi main
```

Note: /LifeInYourWay/ is a symlink pointing to a folder on a mounted drive

**Comment by Elijen** [comment]
I tried the `fs.realpathSync` trick, but it seems that symlinked modules are still not transpiled. For some reason they are included in the build as ES6 (build passes, but browser complains).

I used `yarn link` and `yarn link module-name` to link the module.

**Comment by soluml** [comment]
@eagsalazar's suggestion of using `resolveLoader` worked for my predicament.  I didn't need to set `resolve` or use `fs.realPathSync`.

**Comment by Undistraction** [comment]
For anyone trying the `resolveLoader` approach with Webpack 2, the Webpack 2 equivalent of `root` seems to be `modules`, however this doesn't work. The only solution that works for me with Webpack 2 was to use `fs.realpathSync`. 

Anyway, @eagsalazar's suggestion of using an absolute path for the value of `root` (or now `modules` might be problematic - see [docs](https://webpack.js.org/configuration/resolve/#resolve-modules)).

**Comment by DenisVuyka** [comment]
The `modules` approach does not work with Webpack 2. Sometimes it works when there's only 1 symlink, but once there are many of them (based on my scenario - 15) it stops working completely. For now, have to copy files to `node_modules` instead of using symlinks. but this is far from what I've expected to have with Webpack 2 to be honest.

**Comment by Undistraction** [comment]
@DenisVuyka Yep. Trying to work with linked modules in Webpack 2 is proving to be nightmare. I've wasted a horrible amount of time on related issues.

**Comment by DenisVuyka** [comment]
@Undistraction It is much better than Webpack 1 based on my experiments. Setting up 1 project with 1 symlink it usually a breeze. The problem is that it seems nobody tested the flow beyond 1 symlink.

**Comment by tfsimondouglas** [comment]
Trying to remove the emotion here, but this really needs to be fixed: Ticket still unresolved for 68 weeks...

**Comment by elado** [comment]
#### Updating followers of this ticket:

I ditched the symlink approach; instead, I created another node module which compiles on its own with babel that is locally linked. That package has this in `package.json`:

```js
"name": "awesome-module",
"main": "lib/index.js",
"scripts": {
  "build:clean": "rimraf dist lib",
  "build:ensure": "mkdir -p lib",
  "build:js": "npm run build:ensure && babel -d lib/ src/ -s inline",
  "build": "npm run build:clean && npm run build:ensure && npm run build:js",
  "watch:js": "npm run build:js -- -w",
  "watch": "npm run build && npm run watch:js",
  "postinstall": "npm run build",
  // ...
}
```

And `src/index.js` etc.

Then execute `npm link` in that dir, which registers the module globally on my machine, and `npm link awesome-module` in my initial module. That way, webpack isn't responsible for that module.

Also running `npm run watch` to have files updated on save.

**Comment by Undistraction** [comment]
@elado Thanks for the info, but using `npm link` or `yarn link` is just using symlinks under the hood isn't it? `npm link` creates a symlink in your user dir, then `npm link x` creates another symlink from the dir in `node_modules` to this symlink.

**Comment by elado** [comment]
@Undistraction correct, but the idea is  to have webpack only include the other module without transpiling it with babel-loader. It's already compiled by babel on its own, and looks like any other ES5 module.

**Comment by Undistraction** [comment]
@elado Sorry. Was getting confused with one of other bugs related to symlinks I've been hitting -  #985 - which is just a general issue with symlinked files, not specifically related to compilation. Can see how your solution negates this issue.

**Comment by mikefisher84** [comment]
Still can't quite get this to work with Webpack 2.2.1 on node 6.10.0 even using the fs.realpathsync approach. 

```
var includePaths = [
	fs.realpathSync(__dirname + '/src'),
	fs.realpathSync(__dirname + '/node_modules/my-core-services'),
	fs.realpathSync(__dirname + '/node_modules/my-view-modules'),
];

module: {
   {test: /\.js$/, include: includePaths, use: ['babel-loader']},
}

```

I have external javascript modules in a separate package that need to be compiled. 

When I console log the includePaths I see

```
'/Users/mike/Dev/my-core-services',     <==== npm linked
 '/Users/mike/Dev/myapp/node_modules/my-view-modules' <==== not npm linked
```

However when I run webpack all the javascript in the npm linked module throws compile errors as it doesn't recognize the syntax I'm using. Not sure what I'm missing here. Any ideas?

**Comment by zandroid** [comment]
Not the same problem but similar to this is resolved for me by `--preserve-symlinks` node option.

I needed to load symlinked ES6 script (with `export` & `import`) that is outside from project root with `babel-register`. Without node option this script was not compiled by babel. But with option `--preserve-symlinks` it works fine.

**Comment by Alex-Mann** [comment]
@elado I've been using the same approach but I'm experiencing issues with resolving a file with npm link... keeps giving me the error `Error: Cannot find module "." at webpackMissingModule`

Ever have this happen to you? If so, any suggestions?

**Comment by kazazor** [comment]
Now with npm 5 all `file` dependencies are symlinks. So this just become a bigger issue.
Can we add native support in webpack for these cases? Something like a parameter says if this is a symlink or not..

**Comment by mass85** [comment]
I experience similar problem in monorepo created with `lerna`, where application built with webpack requires a module that is installed in node_modules as a link. That module is not transpiled.

I have created example repository that reproduces this problem: https://github.com/mass85/no_transpilation_with_lerna

**Comment by earnubs** [comment]
Try setting `resolve.symlinks` to false (https://webpack.js.org/configuration/resolve/#resolve-symlinks), worked for me, YMMV.

**Comment by mass85** [comment]
@earnubs, It did not help.

**Comment by earnubs** [comment]
@mass85 Pity.

Worked in my case because babel-loader was no longer passing a path outside of project root to babel-core, babel-core was then no longer looking outside of project root for a `.babelrc`, and not finding it, and not compiling. Maybe there is an option to make that fail more loudly ... but I guess it would be with babel-core?

**Comment by sebelga** [comment]
For me, with webpack 3, the only thing I had to do is
- Add the include path to my symlink package
- Add an alias in the resolve for that package

With those 2, it works perfectly! 👍

**Comment by leopoldw** [comment]
@sebelga can you post your code examples? Is the alias pointing to the symlink or no? Tried this with 3 and it didn't work...

**Comment by ggondim** [comment]
The solution of @jraede worked for me when using the following configuration:

- Windows user (symlinks and webpack seem to work without any workaround in Linux - I use Ubuntu 16.04 LTS, but it failed with my colleague using Windows 7)
- private scoped npm package
- less, styles, css, babel and ngannotate loaders
- webpack 1 

Just added to `webpack.config.js` as he suggested:
```javascript
const fs = require('fs');
const includes = [
 fs.realpathSync(`${__dirname}/src`),
 fs.realpathSync(`${__dirname}/node_modules/@organization/projects`),
];
config.module = [
  {
    test: /\.js$/,
    loader: 'ng-annotate!babel',
    include: includes,
    exclude: /node_modules/,
  }, {
    test: /\.less$/,
    loader: 'style!css!less',
    include: includes,
  }
];
```

**Comment by FanXiang** [comment]
@earnubs it's works. thanks !

**Comment by httpete** [comment]
I am on the latest webpack 2.11.1 and latest wds. These lines allow me to use my file:.. linked packages in package.json for local dev symlinked and have them update when I change it. The key is the path.resolve you want to make sure you point it to the TOP and only the top node_modules.

`            modules: [
                path.resolve(path.join(__dirname, 'node_modules'))
            ],
            symlinks: true,`

**Comment by dilas12345** [comment]
hi,

i have been working on a web app using reactjs but when i run "npm start" it 
always print "Failed to compile.
Error in Cannot find module 'commondir'
 @ multi main"

is there anything i can do to solve this please.

i tried running npm install commondir but still did not work.
and also remove node_modules and install again nothing 
seems to change.

thanks

**Comment by HyperCed** [comment]
I was able to fix that problem modifying webpack.dev.conf.js which is in build folder.
As you see, in this file, you'll find something like 
new CopyWebpackPlugin([
      {
        from: path.resolve(__dirname, '../static'),
        to: config.dev.assetsSubDirectory,
        ignore: ['.*']
      }

I added some files to copy which are symlinks (lib for example). So I have static/lib --> ../../../lib
And I added this code to CopyWebpackPlugin 
new CopyWebpackPlugin([
      {
        from: path.resolve(__dirname, '../static'),
        to: config.dev.assetsSubDirectory,
        ignore: ['.*']
      },
        {
        from: path.resolve(__dirname, '../static/lib'),
        to: config.dev.assetsSubDirectory+'/lib',
        ignore: ['.*']
      }

**Comment by DjRAST** [comment]
> 
> 
> Try setting `resolve.symlinks: false` (https://webpack.js.org/configuration/resolve/#resolve-symlinks), worked for me, YMMV.

Also worked for us! If you have a symlink to a folder outside of your project root, this seems to be the way. Because otherwise the symlinked folder is resolved in an absolute path which is outside the project root and is then being ignored

**Comment by lizhengnacl** [comment]
`node v10.15.3` `webpack 4.35.3`

the following works for me.

```
include: [
  path.resolve(__dirname, 'src'),
],
exclude: [
  path.resolve(__dirname, 'node_modules')
],
```

**Comment by matzeeable** [comment]
I figured out that `babel-loader` can not resolve modules outside of the project. For example I am using `lerna@3` and `webpack@4.41.2`. After debugging I ended up that `@babel/parser` is responsible for the "issue" (I do not think it's an issue, more a CWD problem) because the plugins and loaders could not be resolved to `node_modules`. There is also an interesting article about that in the babel configuration: https://babeljs.io/docs/en/config-files#monorepos

However, after moving all my babel configs (originally from `package.json#babel`) to my `webpack.config.js` it works without any problems:

```js
// [...]
{
    test: /\.tsx$/,
    exclude: /(disposables)/,
    use: {
        loader: "babel-loader?cacheDirectory",
        options: require("./package.json")).babel
    }
}
// [...]
```

References:
- https://github.com/lerna/lerna/issues/1656

**Comment by TotooriaHyperion** [comment]
> Try setting `resolve.symlinks: false` (https://webpack.js.org/configuration/resolve/#resolve-symlinks), worked for me, YMMV.
This work for me.

Try this solution when using lerna(monorepo with symlink) with webpack, you might find the loader trying to load what should be excluded.
It's because webpack resolve it to nearest relative path, so the path don't have a node_modules in it, thus not excluded.

Keywords for search engine: typescript ts-loader symlink lerna webpack
Keywords: export was not found in
Hope people in trouble can find this solution.

**Comment by vankop** [comment]
Should work with `webpack@latest`. Feel free to report new issue with reproducible repo.

**Comment by AmirTugi** [comment]
For me (webpack `4.46.0`) I needed to add an 

```ts
{
  module: {
    rules: [
      oneOf: [
        {
          //The rule I want to fix
          // This is to also include monorepo packages
          include: [/node_modules\/@organization/]
        }
      ]
    ],
  },
  resolve: {
    symlinks: false
  }
}
```

**Comment by baltsevicha** [comment]
> For me (webpack `4.46.0`) I needed to add both `resolve.symlinks: false` **and** add an `include` path to the rule.
> 
> ```ts
> {
>   module: {
>     rules: [
>       {
>         oneOf: [
>           {
>             //The rule I want to fix
>             // This is to also include monorepo packages
>             include: [/node_modules\/@organization/]
>           }
>         ]
>       }
>     ],
>   },
>   resolve: {
>     symlinks: false
>   }
> }
> ```

It works for me, thank you!

**Comment by Ark-kun** [comment]
> Should work with `webpack@latest`.

It does not work for me with v5.71.0 on Windows.

npm linked `absolute_root_path\app\node_modules\some-package` to `absolute_root_path\some-package`

Using `absolute_root_path\app\node_modules\some-package\src` in includes does not work.
Using `absolute_root_path\some-package\src` in includes works.

The hack from https://medium.com/capriza-engineering/sharing-source-code-and-libraries-in-react-bd30926df312 step 5.1/5 is still required.

@vankop Are you sure webpack checks the paths against the include patterns **both** before and after resolving the symlinks?

**Comment by vankop** [comment]
there is nothing todo with `module.rules` here.. only resolve option make sense. make sure `resolve.symlinks=true` https://webpack.js.org/configuration/resolve/#resolvesymlinks . 

Otherwise please add `infrastructureLogging.debug=true` https://webpack.js.org/configuration/other-options/#debug and post stdout here ( there should be log from resolver )

**Comment by talesAtTilt** [comment]
```
resolve: {
    symlinks: false
}
```
That was enough for me. Thank you folks.

**Comment by felipecrs** [comment]
Note that using `resolve.symlinks: false` breaks webpack dependency resolution when they are installed with pnpm or deno.
