### ISSUE TITLE
Dynamic import with npm link'ed module

### ISSUE THREAD

**Issue by CyanoFresh** [webpack/webpack#7810]
# Bug report

**What is the current behavior?**
I can import my npm linked module by default import statement:
```js
import ModuleName from 'ModuleName'
```
but I can't do this by
```js
import('ModuleName').then(...)
```
error: Cannot find module '~ModuleName'
If I delete symbolic link and copy entire folder to the `node_modules` dir - it works

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create module in separate directory (e.g. `ModuleName`) inside project files
2. `cd` there and run `npm link`
3. `cd` to the project root and run `npm link ModuleName`
4. Try to dynamic import it from `node_modules` dir

**What is the expected behavior?**
Import that module 

**Other relevant information:**
webpack version:  3.8.1
Node.js version: v10.5.0
Operating System: windows 10
Additional tools: -

**Comment by ooflorent** [comment]
Could you try using the latest version of webpack 4?

**Comment by CyanoFresh** [comment]
oh, sorry. I've used `create-react-app`. Will try webpack 4

**Comment by sokra** [comment]
I think `create-react-app` disallows building modules outside of the current directory.

Please reproduce with native webpack.

**Comment by CyanoFresh** [comment]
Works with webpack@4.8.3
