### ISSUE TITLE
6 Tests failing with node 6.1.0

### ISSUE THREAD

**Issue by hunterloftis** [webpack/webpack#2499]
Is webpack expected to work with 6.1.0? The ">=0.6" in engines.node suggests so, but the output I get from `git clone`, `git checkout v1.13.0`, `npm install`, `npm test` is:

```
3887 passing (2m)
  19 pending
  6 failing

  1) ConfigTestCases extract-text issue-14 should compile:
     Error: Cannot find module 'webpack/lib/ConcatSource'
      at require (internal/module.js:20:19)
      at require (internal/module.js:20:19)
      at Object.<anonymous> (test/configCases/extract-text/issue-14/webpack.config.js:1:73)
      at require (internal/module.js:20:19)
      at Context.<anonymous> (test/ConfigTestCases.test.js:29:20)

  2) Examples should compile code-splitted-css-bundle:
     Error: Cannot find module 'webpack/lib/ConcatSource'
      at require (internal/module.js:20:19)
      at require (internal/module.js:20:19)
      at Object.<anonymous> (examples/code-splitted-css-bundle/webpack.config.js:1:87)
      at require (internal/module.js:20:19)
      at Context.<anonymous> (test/Examples.test.js:20:15)

  3) Examples should compile css-bundle:
     Error: Cannot find module 'webpack/lib/ConcatSource'
    at require (internal/module.js:20:19)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (examples/css-bundle/webpack.config.js:1:87)
    at require (internal/module.js:20:19)
    at Context.<anonymous> (test/Examples.test.js:20:15)


  4) Examples should compile i18n:
     Error: Cannot find module 'webpack/lib/dependencies/ConstDependency'
    at require (internal/module.js:20:19)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (examples/i18n/webpack.config.js:2:18)
    at require (internal/module.js:20:19)
    at Context.<anonymous> (test/Examples.test.js:20:15)


  5) Examples should compile multiple-entry-points-commons-chunk-css-bundle:
     Error: Cannot find module 'webpack/lib/ConcatSource'
    at require (internal/module.js:20:19)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (examples/multiple-entry-points-commons-chunk-css-bundle/webpack.config.js:3:25)
    at require (internal/module.js:20:19)
    at Context.<anonymous> (test/Examples.test.js:20:15)


  6) Examples should compile web-worker:
     Error: done() invoked with non-Error: Cannot find module 'webpack/lib/webworker/WebWorkerTemplatePlugin'
 @ (webpack)/examples/web-worker/example.js 1:13-39
    at test/Examples.test.js:42:13
    at Compiler.<anonymous> (lib/Compiler.js:194:14)
    at Compiler.emitRecords (lib/Compiler.js:282:37)
    at Compiler.<anonymous> (lib/Compiler.js:187:11)
    at lib/Compiler.js:275:11
    at Compiler.afterEmit (lib/Compiler.js:272:8)
    at Compiler.<anonymous> (lib/Compiler.js:267:14)
    at FSReqWrap.oncomplete (fs.js:117:15)
```

All the errors are missing module error, so I wonder if there's an additional step required to run tests locally.

**Comment by hunterloftis** [comment]
Closing, as this is a duplicate of a still-open issue: https://github.com/webpack/webpack/issues/1819
