### ISSUE TITLE
Cannot find config file after upgrading from 1.7.x to 1.8.x

### ISSUE THREAD

**Issue by alanrsoares** [webpack/webpack#964]
Right after updating to 1.8, the arbitrary path to `webpack.config.js` cannot be resolved, throwing a `module not found` exception.

In my case, all my configurations files live under a `config` folder, eg: `config/webpack.config.js` and `config/webpack.config.js`.

And I call webpack through the CLI:
```bash
./node_modules/.bin/webpack --config config/webpack.dist.config.js --progress -p
```

**Comment by MitMaro** [comment]
Some additional information:

```
$ webpack
module.js:324
    throw err;
          ^
Error: Cannot find module 'webpack.config.js'
    at Function.Module._resolveFilename (module.js:322:15)
    at Function.Module._load (module.js:264:25)
    at Module.require (module.js:351:17)
    at require (module.js:370:17)
    at module.exports (/Users/mitmaro/Code/ComboKeysContext/node_modules/webpack/bin/convert-argv.js:56:12)
    at Object.<anonymous> (/Users/mitmaro/Code/ComboKeysContext/node_modules/webpack/bin/webpack.js:56:40)
    at Module._compile (module.js:446:26)
    at Object.Module._extensions..js (module.js:464:10)
    at Module.load (module.js:341:32)
    at Function.Module._load (module.js:296:12)
```

**Comment by MitMaro** [comment]
Rolling back to version 1.8.2 from 1.8.3 fixes the problem for me.

**Comment by alanrsoares** [comment]
I'm gonna stick with 1.7.x till there's a patch for this issue.

**Comment by claydiffrient** [comment]
For me, if my file is named `webpack.config.js` it works.  If I try passing it in such as `webpack --config webpack.development.js` it throws the `Cannot find module` error.
