### ISSUE TITLE
TypeError: pair[2].integrate is not a function 2.3.0

### ISSUE THREAD

**Issue by DragonFire353** [webpack/webpack#4532]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When I try to compile I get: TypeError: pair[2].integrate is not a function at Compilation.compilation.plugin (*/node_modules/webpack/lib/optimize/MinChunkSizePlugin.js:59:13)

**If the current behavior is a bug, please provide the steps to reproduce.**

Compile that worked on 2.2.1

**What is the expected behavior?**

Compilation success

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

node 7.7.1 on Mac

I do have two configs that compile simultaneously

Client:

new webpack.optimize.MinChunkSizePlugin({
	minChunkSize: 10000
}),

Server:

new webpack.optimize.MinChunkSizePlugin({
	minChunkSize: Infinity
})

And I do use [webpack-hot-server-middleware](https://www.npmjs.com/package/webpack-hot-server-middleware) in case that has anything to do with it.

**Comment by TheLarkInn** [comment]
Would it be possible to provide a reproducible example in a small repo?

**Comment by sokra** [comment]
I got the bug, you don't need a repro repo. Thanks for reporting.

**Comment by TheLarkInn** [comment]
👌
