### ISSUE TITLE
String replace plugin fails with Webpack 2.1 (2.1.0-beta.27)

### ISSUE THREAD

**Issue by mlcohen** [webpack/webpack#3424]
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

I'm trying to upgrade my project from webpack 1.3 to webpack 2.1 (currently 2.1.0-beta.27). In my webpack configuration I'm making use of the string replace webpack plugin (https://github.com/jamesandersen/string-replace-webpack-plugin) which works fine with webpack 1.3 but ends up causing a build error using webpack 2.1. Here is an example of what my config currently looks like with the string replace webpack plugin:

```js
let StringReplacePlugin  = require('string-replace-webpack-plugin');

module.exports = {
    module: {
        rules: [{
            enforce: 'pre',
            test: /\.js$/,
            use: [{
                loader: StringReplacePlugin.replace({
                    pattern: /id="@(\w+):([\w\.]+)"/g,
                    replacement: function (match, p1, p2) {
                        return `id="${p2}" defaultMessage={${p1}.${p2}.message}`
                    }
                })
            }]
        },
        // .... other rules
       ]
    },

    plugins: [
        new StringReplacePlugin()
    ]
} 
```

And here is the build error that I'm getting:

```
ERROR in ./main.js
Module build failed: Error: Cannot find module '/Users/mlc/tmp/app/node_modules/string-replace-webpack-plugin/loader.js?id=n7if95dcsxmh55jdgfhpeewmi'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at loadLoader (/Users/mlc/tmp/app/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/Users/mlc/tmp/app/node_modules/loader-runner/lib/LoaderRunner.js:164:2)
    at iteratePitchingLoaders (/Users/mlc/tmp/app/node_modules/loader-runner/lib/LoaderRunner.js:160:10)
    at /Users/mlc/tmp/app/node_modules/loader-runner/lib/LoaderRunner.js:168:18
    at loadLoader (/Users/mlc/tmp/app/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/Users/mlc/tmp/app/node_modules/loader-runner/lib/LoaderRunner.js:164:2)
    at iteratePitchingLoaders (/Users/mlc/tmp/app/node_modules/loader-runner/lib/LoaderRunner.js:160:10)
    at /Users/mlc/tmp/app/node_modules/loader-runner/lib/LoaderRunner.js:168:18
    at loadLoader (/Users/mlc/tmp/app/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/Users/mlc/tmp/app/node_modules/loader-runner/lib/LoaderRunner.js:164:2)
    at runLoaders (/Users/mlc/tmp/app/node_modules/loader-runner/lib/LoaderRunner.js:357:2)
    at NormalModule.doBuild (/Users/mlc/tmp/app/node_modules/webpack/lib/NormalModule.js:131:2)
    at NormalModule.build (/Users/mlc/tmp/app/node_modules/webpack/lib/NormalModule.js:179:15)
    at Compilation.buildModule (/Users/mlc/tmp/app/node_modules/webpack/lib/Compilation.js:127:9)
    at Compilation.<anonymous> (/Users/mlc/tmp/app/node_modules/webpack/lib/Compilation.js:404:8)
    at /Users/mlc/tmp/app/node_modules/webpack/lib/NormalModuleFactory.js:74:13
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/Users/mlc/tmp/app/node_modules/tapable/lib/Tapable.js:123:70)
    at onDoneResolving (/Users/mlc/tmp/app/node_modules/webpack/lib/NormalModuleFactory.js:49:11)
    at onDoneResolving (/Users/mlc/tmp/app/node_modules/webpack/lib/NormalModuleFactory.js:165:6)
    at /Users/mlc/tmp/app/node_modules/webpack/lib/NormalModuleFactory.js:161:6
    at /Users/mlc/tmp/app/node_modules/webpack/node_modules/async/dist/async.js:3694:9
    at /Users/mlc/tmp/app/node_modules/webpack/node_modules/async/dist/async.js:356:16
    at iteratorCallback (/Users/mlc/tmp/app/node_modules/webpack/node_modules/async/dist/async.js:936:13)
    at /Users/mlc/tmp/app/node_modules/webpack/node_modules/async/dist/async.js:840:16
    at /Users/mlc/tmp/app/node_modules/webpack/node_modules/async/dist/async.js:3691:13
    at apply (/Users/mlc/tmp/app/node_modules/webpack/node_modules/async/dist/async.js:21:25)
```

Any thoughts on how I can address this? Is there a simple fix that can be applied to my webpack config or is this a compatibility issue between the string replace plugin and webpack 2? If it is a compatibility issue, what would need to be changed in the plugin to get everything to work again?

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Copy source code in gist to local directory:

https://gist.github.com/mlcohen/6d338ce0494f5a2e966ef83474b3ab1b

2. `npm install`
3. `node ./node_modules/webpack/bin/webpack.js`

**What is the expected behavior?**

Webpack should successfully produce a bundle without any errors. The string replace plugin will get applied and replace strings based on a given set of matching patterns.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Not a feature request.

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

- Node v6.9.1
- macOS 10.12.1

**Comment by Ive4** [comment]
i think you need add issues to https://github.com/jamesandersen/string-replace-webpack-plugin

**Comment by mlcohen** [comment]
Shall do. Thanks.
