### ISSUE TITLE
webpack has compile errors with Typescript 3.9

### ISSUE THREAD

**Issue by sandersn** [webpack/webpack#10855]
# Bug report

**What is the current behavior?**

webpack currently compiles with 3.8.3, but if you use `typescript@rc` instead (3.9.1-rc), you get the following 9 errors:

```
lib/ExternalModule.js(305,28): error TS2554: Expected 1 arguments, but got 0.
lib/Stats.js(68,31): error TS2554: Expected 3 arguments, but got 2.
lib/library/SystemLibraryPlugin.js(127,35): error TS2554: Expected 1 arguments, but got 0.
lib/optimize/ConcatenatedModule.js(205,32): error TS2554: Expected 1 arguments, but got 0.
lib/wasm-async/AsyncWebAssemblyModulesPlugin.js(36,15): error TS2304: Cannot find name 'Chunk'.
lib/wasm-async/AsyncWebAssemblyModulesPlugin.js(37,15): error TS2304: Cannot find name 'DependencyTemplates'.
lib/wasm-async/AsyncWebAssemblyModulesPlugin.js(38,15): error TS2304: Cannot find name 'RuntimeTemplate'.
lib/wasm-async/AsyncWebAssemblyModulesPlugin.js(39,15): error TS2304: Cannot find name 'ModuleGraph'.
lib/wasm-async/AsyncWebAssemblyModulesPlugin.js(40,15): error TS2304: Cannot find name 'ChunkGraph'.
```

If you compile with the version from master, you get 12 additional errors:

```
lib/AbstractMethodError.js(26,16): error TS2532: Object is possibly 'undefined'.
lib/ContextModule.js(333,29): error TS2345: Argument of type 'Error' is not assignable to parameter of type 'WebpackError'.
  Type 'Error' is missing the following properties from type 'WebpackError': details, module, loc, hideStack, and 4 more.
lib/ExternalModule.js(305,28): error TS2554: Expected 1 arguments, but got 0.
lib/MainTemplate.js(40,29): error TS1016: A required parameter cannot follow an optional parameter.
lib/ModuleGraphConnection.js(23,3): error TS1016: A required parameter cannot follow an optional parameter.
lib/Stats.js(68,31): error TS2554: Expected 3 arguments, but got 2.
lib/config/normalization.js(27,30): error TS1016: A required parameter cannot follow an optional parameter.
lib/config/normalization.js(37,38): error TS1016: A required parameter cannot follow an optional parameter.
lib/config/normalization.js(47,29): error TS1016: A required parameter cannot follow an optional parameter.
lib/config/normalization.js(56,37): error TS1016: A required parameter cannot follow an optional parameter.
lib/library/SystemLibraryPlugin.js(127,35): error TS2554: Expected 1 arguments, but got 0.
lib/library/UmdLibraryPlugin.js(38,31): error TS1016: A required parameter cannot follow an optional parameter.
lib/optimize/ConcatenatedModule.js(205,32): error TS2554: Expected 1 arguments, but got 0.
lib/util/fs.js(57,23): error TS1016: A required parameter cannot follow an optional parameter.
lib/util/fs.js(78,19): error TS1016: A required parameter cannot follow an optional parameter.
lib/util/fs.js(98,22): error TS1016: A required parameter cannot follow an optional parameter.
lib/wasm-async/AsyncWebAssemblyModulesPlugin.js(36,15): error TS2304: Cannot find name 'Chunk'.
lib/wasm-async/AsyncWebAssemblyModulesPlugin.js(37,15): error TS2304: Cannot find name 'DependencyTemplates'.
lib/wasm-async/AsyncWebAssemblyModulesPlugin.js(38,15): error TS2304: Cannot find name 'RuntimeTemplate'.
lib/wasm-async/AsyncWebAssemblyModulesPlugin.js(39,15): error TS2304: Cannot find name 'ModuleGraph'.
lib/wasm-async/AsyncWebAssemblyModulesPlugin.js(40,15): error TS2304: Cannot find name 'ChunkGraph'.
```

That's because typescript is now stricter about javascript marking optional properties. They have to be marked, and occur before non-optional properties.
The wasm-async errors were there all along, but we forgot to make the compiler check otherwise-unused properties of a `@typedef` before 3.9.

`typescript@next` also uses control flow on `this.x` property assignments in constructors to figure out their type. This gives better types (like in ContextModule), but also doesn't know about side effects (like in AbstractMethodError).

**If the current behavior is a bug, please provide the steps to reproduce.**

```sh
$ npm install -g typescript@rc # or typescript@next
$ tsc
```

This is mostly a heads up for the new version. I'll create a PR if I can fix the problems easily.
