### ISSUE TITLE
Object(...) is not a function

### ISSUE THREAD

**Issue by frontendphil** [webpack/webpack#11232]
# Bug report

**What is the current behavior?**

After receiving the update to `4.44.0` our application cannot start anymore. In one of our modules, we export a function as the default export. However, it seems `webpack` is now treating the default as an object, which then cannot be called.

**If the current behavior is a bug, please provide the steps to reproduce.**

I couldn't come up with a minimal repro example. However, this worked in `4.43.0` and stopped in `4.44.0` so I expect that it has something to do with the changes in that particular release.

**What is the expected behavior?**

Function default exports should work.

**Other relevant information:**
webpack version:  4.44.0
Node.js version: 12.x
Operating System: Whatever "Vercel" uses
Additional tools: -

**Comment by evilebottnawi** [comment]
Sorry without reproducible test repo we can't help

**Comment by frontendphil** [comment]
Apparently "fix bug in sideEffects optimization when using export * from "non-esm" and a default export." in the latest release was the culprit.
