### ISSUE TITLE
Error on first run after upgrading webpack to 3.2.0

### ISSUE THREAD

**Issue by bhanu7755** [webpack/webpack#5286]
**Do you want to request a *feature* or report a *bug*?**
No

**What is the current behavior?**
After upgrading webpack to 3.2.0 and loading the app for first time it throws below error 

window.require is not a function
    at Object.__extends.__extends.Object.setPrototypeOf.__proto__
at __webpack_require__
at Object.<anonymous>

But when I refresh browser everything works fine without any issues.
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack: 3.2.0
node: v6.10.1
npm: 4.4.4

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).
