### ISSUE TITLE
TypeError being thrown, "utf8 is not a function"

### ISSUE THREAD

**Issue by jamez14** [webpack/webpack#3922]
**Current behavior**
After updating to webpack v2.2.0-rc.4 from v2.2.0-rc.3, an error is thrown in `/lib/Compiler.js` line 324 that states: `TypeError: utf8 is not a function`. This happens within a Docker environment.

<img width="734" alt="screen shot 2017-01-11 at 3 25 09 pm" src="https://cloud.githubusercontent.com/assets/2854919/21865060/74f06a12-d812-11e6-83e0-97e158f569a7.png">

A commit from 12 days ago seems to have changed this line of code. [See this commit for reference](https://github.com/webpack/webpack/commit/7327ee608a040ec784cc251663be85c2aedac44c#diff-7a14ca420cc4fa7cf55f788246117e7c).

**Reproduction steps**
I run the command: `webpack --config ./webpack.config.js` via a Dockerfile

[webpack.config.js Gist](https://gist.github.com/jamez14/7b77b27cf91cf395debcd936f1e05dac)

**What is the expected behavior?**
Webpack should properly build based on the configuration.

**Comment by TheLarkInn** [comment]
What version of node are you using?

**Comment by jamez14** [comment]
@TheLarkInn Sorry, I read [the release notes](https://github.com/webpack/webpack/releases/tag/v2.2.0-rc.4) but didn't draw the comparison. Our Docker server is still running v0.12 of Node. That explains that. Thanks!

**Comment by TheLarkInn** [comment]
No worries at all thanks for reporting!

**Comment by RyanHirsch** [comment]
I'm having this same issue with node v4.3.2
Updating to latest LTS v6.9.4 does not have the issue

**Comment by TheLarkInn** [comment]
Yup our minimum version supported will be node 4.7. We have it set in the package.json currently and once we publish final release we will also update badge etc. Would be open to PR's to have CLI runtime checks for node version and throw if less than the min version we have set on the "engines" property.
