### ISSUE TITLE
"Cannot find module 'ajv/dist/compile/codegen'" after upgrade from 5.64.1 to 5.64.2

### ISSUE THREAD

**Issue by 2-5** [webpack/webpack#14780]
# Bug report

**What is the current behavior?**

Webpack fails to run after upgrading from 5.64.1 to 5.64.2 with this error:

    [webpack-cli] Error: Cannot find module 'ajv/dist/compile/codegen'

**Other relevant information:**
webpack version:  5.64.2
Node.js version: 16.13.0
Operating System: Windows 10

**Comment by 2-5** [comment]
Closing since I think is related to another module upgrading `ajv`

**Comment by amitsingh-007** [comment]
I am also facing the same issue. Can you tell which package degradation is causing this issue?
