### ISSUE TITLE
Getting "n is not a function" while loading federated component

### ISSUE THREAD

**Issue by alyaptsev** [webpack/webpack#12204]
# Bug report

**What is the current behavior?**
I get error
```
TypeError: n is not a function
while loading "./App" from 77301
```
when navigating federated component.

**If the current behavior is a bug, please provide the steps to reproduce.**
Host app Module Federation config:
```
new ModuleFederationPlugin({
    name: 'morda',
    library: { type: 'var', name: 'morda' },
    filename: 'remoteEntry.js',
    remotes: {
      'locale-permissions-admin': 'locale_permissions_admin'
    },
    exposes: {
      './Host': './index'
    },
    shared: {
      react: {
        singleton: true,
      },
      'react-dom': {
         singleton: true,
      }
    }
})
```

Remote app Module Federation config:
```
new ModuleFederationPlugin({
    name: 'locale-permissions-admin',
    library: { type: 'var', name: 'locale_permissions_admin' },
    filename: 'remoteEntry.js',
    exposes: {
      './App': '../src/components/App'
    },
    shared: {
      react: {
        singleton: true,
      },
      'react-dom': {
         singleton: true,
      },
      …otherDeps
    }
})
```
This worked for version 5.0.0-beta29, but after upgrading to 5.10.0 started to get error. After reading troubleshooting section of docs added host remoteEntry, but problem hasn’t solved

**What is the expected behavior?**
Federated component should be shown when navigating the route

**Other relevant information:**
webpack version:  5.10.0
Node.js version: 12.6
Operating System: MacOS 10.4.6

**Comment by alexander-akait** [comment]
Something wrong with your code, I can't say what, because you don't provide more information

**Comment by csvan** [comment]
@alyaptsev are you using the dev-server to serve your federated module?

**Comment by alyaptsev** [comment]
Umm, what kind of more information do you need?

I'm including component via React.lazy
```
const LocalePermissionsPage = React.lazy(() => import('locale-permissions-admin/App'))
<Route
  path="myPath"
  component={
    <React.Suspense fallback="Loading...">
     <LocalePermissionsPage />
    </React.Suspense>
  }
/>
```
LocalePermissionsPage is a full-featured React component with store, hooks and 3rd-parties

I ensured that host remoteEntry.js and page remoteEntry.js loaded

**Comment by alexander-akait** [comment]
Minimum - reproducible example, module federation is not simple and there are a lot of places where can a mistake be made (you can see you configuration is simple). Do you understand that after copying your code, I did not get an error? So I can't say what is wrong.

And yes webpack-dev-server is not supported module federation yet

**Comment by alyaptsev** [comment]
@csvan no, it's served as static files

**Comment by alexander-akait** [comment]
@alyaptsev friendly ping

**Comment by alexander-akait** [comment]
Closing due to inactivity. Please test with latest version and feel free to reopen if still regressions. Thanks!

**Comment by tm-bonrepublic** [comment]
I experienced this issue with webpack 5. `webpackConfig.output.uniqueName` was missing in my case, defaulting to name from package.json, causing this runtime error in production build only.
