### PR TITLE
Promote loader-utils from dev dependency

### LINKED ISSUE #1448: Regression in CLI --plugin: Cannot find module 'loader-utils'
Seeing an error when I try to use `--plugin` since v1.12.1. From what I can tell, this was introduced in #1327 where `loader-utils` should have been added as a non-dev dependency. If I `npm install -g loader-utils`, the error goes away.

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'loader-utils'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at loadPlugin (/usr/local/lib/node_modules/webpack/bin/convert-argv.js:202:20)
    at /usr/local/lib/node_modules/webpack/bin/convert-argv.js:500:25
    at ifArg (/usr/local/lib/node_modules/webpack/bin/convert-argv.js:155:5)
    at processOptions (/usr/local/lib/node_modules/webpack/bin/convert-argv.js:498:3)
    at module.exports (/usr/local/lib/node_modules/webpack/bin/convert-argv.js:91:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/webpack/bin/webpack.js:39:40)
```

### PR DESCRIPTION
**Pull request by loganlinn**
Fixes #1448

### CODE REVIEW

**Comment by sokra** [comment]
Thanks
