### ISSUE TITLE
When updating from 5.0.0-beta.26 to 5.0.0-beta.27 build fails

### ISSUE THREAD

**Issue by ChildishGiant** [webpack/webpack#11358]
# Bug report

**What is the current behavior?**
When trying to build I get this:
```
HookWebpackError: asset.source.buffer is not a function
    at makeWebpackError (/home/runner/work/web/web/node_modules/webpack/lib/HookWebpackError.js:49:9)
    at /home/runner/work/web/web/node_modules/webpack/lib/Compilation.js:1978:11
    at eval (eval at create (/home/runner/work/web/web/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
-- inner error --
TypeError: asset.source.buffer is not a function
    at /home/runner/work/web/web/node_modules/webpack/lib/optimize/RealContentHashPlugin.js:213:25
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
caused by plugins in Compilation.hooks.processAssets
TypeError: asset.source.buffer is not a function
    at /home/runner/work/web/web/node_modules/webpack/lib/optimize/RealContentHashPlugin.js:213:25
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:2554) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at /home/runner/work/web/web/config/webpack/config.js:156:22
    at finalCallback (/home/runner/work/web/web/node_modules/webpack/lib/Compiler.js:367:32)
    at onCompiled (/home/runner/work/web/web/node_modules/webpack/lib/Compiler.js:376:20)
    at /home/runner/work/web/web/node_modules/webpack/lib/Compiler.js:974:25
    at /home/runner/work/web/web/node_modules/webpack/lib/Compilation.js:1977:17
    at eval (eval at create (/home/runner/work/web/web/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
An example is here: https://github.com/cloverleaf/web/pull/223/checks?check_run_id=1007353755 
The only thing that changed in this PR is the version number so I'm fairly sure this is the issue.
The config I'm using can be found here but it's not a minimal repro https://github.com/cloverleaf/web/blob/13d58fdbdccfc6918474b1c503959cc80bdbee9a/config/webpack/config.js

**Other relevant information:**
webpack version:  5.0.0-beta.27
Node.js version: v12.18.3
Operating System: Tested on Windows 10 and Ubuntu

**Comment by chenxsan** [comment]
Try to update to beta 28 https://github.com/webpack/webpack/releases/tag/v5.0.0-beta.28, I think it's fixed.
