### ISSUE TITLE
webpack 2.3.2 and external AMD Modules

### ISSUE THREAD

**Issue by KoenigLear** [webpack/webpack#4609]
Bug report -  external AMD modules don't load webpack 2.3.2

**Current behavior**
I have an external amd module mylogger, I load into my pages using requirejs.

I've added externals to my webpack config:
```
    externals: {
        mylogger: true, // b is external (require("b"))
    },
```

when I try to use the module in my code:

```
Cannot find module "mylogger" at webpackMissingModule
```

the module is defined as this:
```
mylogger.js
define("mylogger", [], function () {  ...
```

it's included in my page via require js config
```
require.config({
    baseUrl: '/Applications/',
    paths: {
        'mylogger': 'mylogger'
    }
});
```

Other notes:
a test in the page confirms the module loads correctly (when not using webpack)
```
require(["mylogger"], function (mylogger) { console.log('mylogger loaded'); });
prints 'mylogger loaded'
```

**Expected behavior**
The module loads correctly (e.g no errors) when called (from code within a webpack bundle)
```
import mylogger= require("mylogger");   //typescript
```

which roughly translates to
```
var mylogger = _webpack_require("mylogger")
```

**If this is a feature request, what is motivation or use case for changing the behavior?**
I consider this a bug.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
I'm working with Windows 2012 r2, node 7.5, webpack 2.2

**Comment by sokra** [comment]
Did you set `output.libraryTarget = "amd"`?

**Comment by KoenigLear** [comment]
Hi @sokra, I don't want my calling module to be amd.  I want to call an AMD (mylogger) but not make my code amd.  thanks

**Comment by sokra** [comment]
Could you create a test repo with a minimal test repro case?

**Comment by KoenigLear** [comment]
@sokra  before I do that, I have more details:  

It turns out that using externals: ["mylogger"] generates:
eval("module.exports = mylogger; });//# sourceMappingURL...");

after hacking the bundle and changing it to

eval("define(function (require, exports, module) { module.exports = istats1; });//# sourceMappingURL...");

it works!!   I tried the output.libraryTarget but this puts everything in the bundle within a define block which is not desirable.  It's needed only for specific external libraries.

**Comment by KoenigLear** [comment]
@sokra  see attached sample with the detailed problem:

the page index.html tries to load the module both ways:
- inside dist/bundle.js  created with webpack  this doesn't work!
- outside via MyloggerTest.js      this works!

For simplicity Mylogger.log  just logs to the console any message.

[webpackissue.zip](https://github.com/webpack/webpack/files/890737/webpackissue.zip)
](url)

**Comment by sokra** [comment]
I see two ways here:

* `libraryTarget: "amd"` this wrapps the whole bundle in a define block. This is needed because require.js need to delay module execution until mylogger is loaded. (remember loading the mylogger file is async)
* use `requirejs(["mylogger"], ...)` to load the mylogger lib async via require.js.

There is no way to replace the `...` in `module.exports = ...` with code which loads any module via require.js because require.js wants to load the module async and this code fragment is sync. The only option is to wrap it in a define block, so require.js is able to delay the execution until all dependencies are loaded.

**Comment by KoenigLear** [comment]
@sokra  I'm trying to do number two in the attached sample but still doesn't work.

```
    require(["Mylogger"], function (logger: Mylogger) {
        console.log("inside");
        logger.log("hello");
    });
```

I get a:
` Uncaught (in promise) ReferenceError: Mylogger is not defined`

**Comment by sokra** [comment]
`require` -> `requirejs`

`require` is handled by webpack, but it ignores `requirejs`.

**Comment by KoenigLear** [comment]
@sokra  many thanks happy to close :)
