### ISSUE TITLE
webpack 4.0.0-alpha.1 feedback

### ISSUE THREAD

**Issue by sokra** [webpack/webpack#6132]
Changelog diff from [4.0.0-alpha.0](https://github.com/webpack/webpack/issues/6064)

# Big features

* Upgrade uglifyjs-webpack-plugin to v1
  * ES15 support
* `optimization.minimize` has been added to switch minimizing on/off
  * By default: on in production mode, off in development mode
* `optimization.minimizer` has been added to configurate minimizers and options
* CLI has been move to webpack-cli, you need to install `webpack-cli` to use the CLI
* The ProgressPlugin (`--progress`) now displays plugin names
  * At least for plugins migrated to the new plugin system

# Features

* Parser now understand `new Foo()` expressions
* Parser can now evaluate `**`, `&`, `|`, `^`, `>>>`, `>>`, `<<` and `~`
* `Rule.ident` is now allowed by schema
* constant replacements now don't need `__webpack_require__` and argument is omitted
* The concatenated module now generates a bit less code
* `sideEffects` can be overriden via module.rules

# Bugfixes

* WebAssembly modules are now correctly threaded as ESM modules and export their exports directly instead of wrapping the content in a default export
* Extensions are resolved normally in *.mjs again

# Breaking changes for Plugin authors

* Methods on `Template` are now static
* A new RuntimeTemplate class has been added and `outputOptions` and `requestShortener` has been moved to this class
  * Many methods has been updated to use the RuntimeTemplate instead
  * We plan to move code which accesses the runtime to this new class
* `Module.meta` has been replaced with `Module.buildMeta`
* `Module.buildInfo` and `Module.factoryMeta` have been added
* Some properties of `Module` have been moved into the new objects

---

*Please comment if you find additional changes not in the changelog*

**Comment by yamafaktory** [comment]
Hi, awesome work 👍.

When upgrading to `webpack 4.0.0-alpha.1` in conjonction with `webpack-dev-server 3.0.0-alpha5` (I also added `webpack-cli 1.5.2`), I get the following error:

```sh
module.js:529
    throw err;
    ^

Error: Cannot find module 'webpack/bin/convert-argv'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/yamafaktory/dev/rust-wasm-webpack/node_modules/webpack-dev-server/cli.js:8:21)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

**Comment by TheLarkInn** [comment]
Linking over #6135

**Comment by phyllisstein** [comment]
Looks like the `plugin` call is still not working as expected with `MultiCompiler`; it's currently causing issues with `webpack-dev-middleware`'s support for multiple compiler instances, as noted in [this comment](https://github.com/webpack/webpack/issues/6064#issuecomment-350434888) and [this issue](https://github.com/webpack/webpack-dev-middleware/issues/236). My Webpack config and other germane details are linked from both of those comments, but I'm happy to provide more color if it's useful. Thanks!

**Comment by TheLarkInn** [comment]
Thank you very much for the report @phyllisstein

**Comment by sompylasar** [comment]
https://github.com/amireh/happypack/issues/200
Looks like one more breaking change: `compiler.resolvers.loader.resolve` is `undefined`.

**Comment by sokra** [comment]
> but compiler.resolvers doesn't seem to be undefined.

There is a kind of compat layer on `compiler.resolvers`.

**Comment by TheLarkInn** [comment]
Adding https://github.com/webpack/webpack/issues/6157

**Comment by peter-mouland** [comment]
I've just created this issue within webpack-cli, seems like it might be related to the `optimization.minimize` options now on by default, but the cli still expects the file to exist within webpack.

`var UglifyJsPlugin = require("webpack/lib/optimize/UglifyJsPlugin"); `

https://github.com/webpack/webpack-cli/blob/2402117ae70ce709b059c60026267f7707becb22/bin/convert-argv.js#L512

https://github.com/webpack/webpack-cli/issues/221

**Comment by donaldpipowitch** [comment]
An answer to @machineloop from the last alpha

> I'm getting the following when I bump up to v4 Alpha, what's the best way to figure out which plugin is breaking?
> ```
> Running "webpack:build" (webpack) task
> Warning: this.compiler.applyPluginsAsync is not a function Used --force, continuing.
> (node:59256) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
> (node:59256) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
> ```

You can run `$ node --trace-deprecation ./node_modules/.bin/webpack`. Now you get:

```
(node:52664) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
    at webpack (./node_modules/webpack/lib/webpack.js:31:19)
    at ...
(node:52664) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at HtmlWebpackPlugin.apply (./node_modules/html-webpack-plugin/index.js:59:12)
    at ...
(node:52664) DeprecationWarning: The callback argument was splitted into resolveContext and callback.
    at Resolver.resolve (./node_modules/enhanced-resolve/lib/Resolver.js:139:15)
    at ...
```

**Comment by sokra** [comment]
new version: https://github.com/webpack/webpack/issues/6179
