### ISSUE TITLE
import() breaks in Angular 7.2.3 + Webpack 4.28

### ISSUE THREAD

**Issue by jslegers** [webpack/webpack#8777]
# Bug report

**What is the current behavior?**

`import(path)` works fine in my Electron demo (which uses 3.12) but fails in my Angular (which uses Webpack 4.28).

**If the current behavior is a bug, please provide the steps to reproduce.**

I have the following code :

````js
var path = "./relative/path/to/" + fileName + ".json";
import(path).then(cb);
````

The `import` works as expected in my Electron demo (which uses Webpack 3.12).

It breaks in my Angular demo (which uses Webpack 4.28).

My Angular demo has the following Webpack config : 
````js
module.exports = {
  node: { fs: 'empty' }
};
````
It produces the following error at runtime :
````js
Unhandled Promise rejection: Cannot find module './resources/symbology/labelTemplates/labelTemplates.json' ; Zone: <root> ; Task: Promise.then ; Value: Error: Cannot find module './resources/symbology/labelTemplates/labelTemplates.json'
    at symbology lazy namespace object:5
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:391)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:150)
    at zone.js:889
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at drainMicroTaskQueue (zone.js:601) Error: Cannot find module './resources/symbology/labelTemplates/labelTemplates.json'
...
````

I tried various changes to my config, but I keep getting the same error.

**What is the expected behavior?**

`import(path).then(cb)` loads the expected JSON file in both 3.12 & 4.28.

**Other relevant information:**
webpack version:  4.28
Node.js version: 10.15.1
Operating System: Windows 10

**Comment by siddhant1** [comment]
I don't think import() syntax works in angular , for code spliiting try 
https://toddmotto.com/lazy-loading-angular-code-splitting-webpack

for Vue.js import() based code splitting works out of the box.
for ReactJs use Suspense based code splitting or React Loadable

**Comment by jslegers** [comment]
Unfortunately, the work is focused on a library ([LuciadRIA](https://www.hexagongeospatial.com/products/luciad-portfolio/luciadria)), which is supposed to work in any environment.

I can not assume our code will be run in either Angular, Vue, React, etc. It should be compatible with each of these environments, with as little custom configuration as possible.

Thus, if it is not possible to do code splitting the same way across these different environments, the only option we have is to avoid code splitting and opt for a different approach.
