### ISSUE TITLE
stampit___default.a(...).props is not a function in Webpack 3

### ISSUE THREAD

**Issue by jktravis** [webpack/webpack#5241]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I get an error at runtime that states:

    TypeError: __WEBPACK_IMPORTED_MODULE_0_stampit___default.a(...).props is not a function

Nothing changed (that I can tell) with the `stampit` library or the module that uses it when transitioning from Webpack 2.5.1 to 3.1.0

**If the current behavior is a bug, please provide the steps to reproduce.**
I created a repo that demonstrates the problem. 

https://github.com/jktravis/Webpack3StampIt

**What is the expected behavior?**
No error.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Chrome 59
Windows 10
Webpack 3.1.0 (but it was also there in 3.0.0, but not in 2.5.1)
Node 7.8.0

**Comment by pksjce** [comment]
@jktravis - Hey I tried this out. 
Firstly, I'm not sure what the issue is and I'm not completely familiar with how `stampit` works.
But I found that changing https://github.com/jktravis/Webpack3StampIt/blob/master/src/stamps.js#L3 
`stampit().props -> stampit.props` makes it work with `webpack@2.6.1` and with `webpack@latest`.
Does that help?

**Comment by koresar** [comment]
This is stampit bug. Thank you

**Comment by jktravis** [comment]
Thanks, @koresar.

**Comment by TheLarkInn** [comment]
hank you for confirming @jktravis
